const cars=[...JSON.parse(localStorage.getItem('vkluche-listings')||'[]'),
 {id:1,name:'BMW X5 xDrive30d',price:7890000,year:2023,km:'18 400 км',engine:'3.0 л / 249 л.с.',city:'Москва',date:'сегодня',type:['used','suv'],badge:'Проверено',img:'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=900&q=80'},
 {id:2,name:'Mercedes-Benz C-Класс',price:4750000,year:2022,km:'31 200 км',engine:'2.0 л / 197 л.с.',city:'Казань',date:'сегодня',type:['used'],badge:'Хорошая цена',img:'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=900&q=80'},
 {id:3,name:'Geely Monjaro Flagship',price:4189000,year:2025,km:'Новый',engine:'2.0 л / 238 л.с.',city:'Самара',date:'вчера',type:['new','suv'],badge:'Новый',img:'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=900&q=80'},
 {id:4,name:'Audi A6 45 TFSI',price:5390000,year:2022,km:'27 800 км',engine:'2.0 л / 245 л.с.',city:'Москва',date:'сегодня',type:['used'],badge:'Проверено',img:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=80'},
 {id:5,name:'Tesla Model 3 Long Range',price:4360000,year:2023,km:'12 100 км',engine:'498 л.с. / AWD',city:'Москва',date:'2 часа назад',type:['used','electric'],badge:'Электро',img:'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=900&q=80'},
 {id:6,name:'Porsche Macan S',price:9560000,year:2021,km:'42 000 км',engine:'3.0 л / 354 л.с.',city:'Санкт-Петербург',date:'вчера',type:['used','suv'],badge:'Оригинал ПТС',img:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80'},
 {id:7,name:'Toyota Camry 2.5',price:3640000,year:2021,km:'51 300 км',engine:'2.5 л / 181 л.с.',city:'Самара',date:'сегодня',type:['used'],badge:'1 владелец',img:'https://images.unsplash.com/photo-1621993202323-f438eec934ff?auto=format&fit=crop&w=900&q=80'},
 {id:8,name:'EXEED RX Platinum',price:5250000,year:2025,km:'Новый',engine:'2.0 л / 249 л.с.',city:'Казань',date:'3 часа назад',type:['new','suv'],badge:'Новый',img:'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=900&q=80'}
];
const extraPhotos=['https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1200&q=85'];
const demoAuctionCar=cars.find(car=>car.id===1);if(demoAuctionCar&&!demoAuctionCar.auction)demoAuctionCar.auction={status:'active',startPrice:7350000,reservePrice:7700000,bidStep:10000,endsAt:Date.now()+2*60*60*1000,autoExtend:true,bids:[{id:'demo-1',buyer:'АвтоПрайм',amount:7480000,comment:'Выездной осмотр сегодня',rating:4.9,createdAt:Date.now()-22*60*1000},{id:'demo-2',buyer:'Мотор Групп',amount:7560000,comment:'Оплата в день осмотра',rating:4.8,createdAt:Date.now()-8*60*1000}]};
if(demoAuctionCar?.auction){demoAuctionCar.badge='Аукцион';demoAuctionCar.price=auctionBest(demoAuctionCar.auction)}
const auctionOverrides=JSON.parse(localStorage.getItem('vkluche-auction-overrides')||'{}');cars.forEach(car=>{const savedAuction=auctionOverrides[car.id];if(savedAuction)Object.assign(car,savedAuction)});
let activeFilter='all',saved=new Set(JSON.parse(localStorage.getItem('vkluche-favs')||'[]'));
const grid=document.querySelector('#carsGrid'),count=document.querySelector('#resultCount'),empty=document.querySelector('#emptyState');
const auctionGrid=document.querySelector('#auctionGrid'),auctionEmpty=document.querySelector('#auctionEmpty');
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const filterForm=document.querySelector('#advancedFilters'),filterPanel=document.querySelector('#filterPanel'),filterBackdrop=document.querySelector('#filterBackdrop');
const checkedValues=name=>[...filterForm.querySelectorAll(`[name="${name}"]:checked`)].map(input=>input.value);
function inSelectedRanges(value,name){const ranges=checkedValues(name);return!ranges.length||ranges.some(range=>{const[min,max]=range.split('-').map(Number);return value>=min&&value<=max})}
function inCustomOrSelectedRange(value,fromSelector,toSelector,name){const fromField=document.querySelector(fromSelector),toField=document.querySelector(toSelector),hasCustom=fromField.value!==''||toField.value!=='';if(!hasCustom)return inSelectedRanges(value,name);const from=fromField.value===''?0:+fromField.value,to=toField.value===''?Infinity:+toField.value;return value>=from&&value<=to}
const carMileage=car=>car.km==='Новый'?0:Number(String(car.km).replace(/\D/g,''))||0;
function carBrand(car){if(car.details?.brand)return car.details.brand;return Object.keys(carModels||{}).sort((a,b)=>b.length-a.length).find(brand=>car.name===brand||car.name.startsWith(`${brand} `))||car.name.split(' ')[0]}
function carModel(car){if(car.details?.model)return car.details.model;const brand=carBrand(car);return car.name.slice(brand.length).trim()}
function carGearbox(car){const value=String(car.details?.gearbox||'Автомат').toLowerCase();if(/механ|\bmt\b/.test(value))return'Механика';if(/вариат|cvt/.test(value))return'Вариатор';if(/робот|dct|dsg/.test(value))return'Робот';return'Автомат'}
function carEngineType(car){const value=String(car.details?.engineType||'').toLowerCase();if(car.type.includes('electric')||/элект|electric|ev/.test(value))return'electric';if(/гибрид|hybrid|phev|hev/.test(value))return'hybrid';if(/диз|diesel/.test(value)||/\d+d\b/i.test(car.name))return'diesel';if(/газ|lpg|cng/.test(value))return'gas';return'petrol'}
const engineTypeLabels={petrol:'Бензин',diesel:'Дизель',hybrid:'Гибрид',electric:'Электромотор',gas:'Газ'};
function carDrive(car){return car.details?.drive||(car.type.includes('suv')?'Полный':'Передний')}
function carBody(car){return car.details?.body||(car.type.includes('suv')?'Кроссовер':'Седан')}
function matchesAdvanced(c){const brands=checkedValues('filterBrand'),models=checkedValues('filterModel'),gearboxes=checkedValues('filterGearbox'),engines=checkedValues('filterEngine'),bodies=checkedValues('filterBody'),drives=checkedValues('filterDrive'),conditions=checkedValues('filterCondition'),cities=checkedValues('filterCity'),brand=carBrand(c),model=carModel(c);return(!brands.length||brands.includes(brand))&&(!models.length||models.some(value=>{const[selectedBrand,selectedModel]=value.split('|||');return selectedBrand===brand&&(model===selectedModel||model.startsWith(`${selectedModel} `))}))&&inCustomOrSelectedRange(c.price,'#filterPriceFrom','#filterPriceTo','filterPrice')&&inCustomOrSelectedRange(c.year,'#filterYearFrom','#filterYearTo','filterYear')&&inCustomOrSelectedRange(carMileage(c),'#filterMileageFrom','#filterMileageTo','filterMileage')&&(!gearboxes.length||gearboxes.includes(carGearbox(c)))&&(!engines.length||engines.includes(carEngineType(c)))&&(!bodies.length||bodies.includes(carBody(c)))&&(!drives.length||drives.includes(carDrive(c)))&&(!conditions.length||conditions.some(value=>c.type.includes(value)))&&(!cities.length||cities.includes(c.city))}
function filtered(){const q=document.querySelector('#searchInput').value.toLowerCase(),max=+document.querySelector('#priceInput').value||Infinity,city=document.querySelector('#cityInput').value;let out=cars.filter(c=>(activeFilter==='all'||c.type.includes(activeFilter))&&c.price<=max&&(!city||c.city===city)&&(!q||`${c.name} ${c.engine}`.toLowerCase().includes(q))&&matchesAdvanced(c));const s=document.querySelector('#sortSelect').value;if(s==='low')out.sort((a,b)=>a.price-b.price);if(s==='high')out.sort((a,b)=>b.price-a.price);if(s==='year')out.sort((a,b)=>b.year-a.year);if(s==='mileage')out.sort((a,b)=>carMileage(a)-carMileage(b));return out}
function render(){const data=filtered();grid.innerHTML=data.map(c=>`<article class="car-card"><div class="car-image"><img src="${c.img}" alt="${c.name}" loading="lazy"><span class="badge">${c.badge}</span><button class="fav-btn ${saved.has(c.id)?'saved':''}" data-id="${c.id}" aria-label="В избранное">${saved.has(c.id)?'♥':'♡'}</button></div><div class="car-content"><h3>${c.name}</h3><div class="price">${money(c.price)}</div><div class="car-meta"><span>${c.year}</span><span>${c.km}</span><span>${c.engine}</span><span class="engine-type"><small>Тип двигателя</small><b>${engineTypeLabels[carEngineType(c)]}</b></span></div><div class="car-location"><span>⌖ ${c.city}</span><span>${c.date}</span></div></div></article>`).join('');count.textContent=data.length?`Подобрали ${data.length} отличных вариантов`:'Нет подходящих вариантов';empty.style.display=data.length?'none':'block';grid.style.display=data.length?'grid':'none';document.querySelector('#loadMore').style.display=data.length?'block':'none';document.querySelector('#favCount').textContent=saved.size}
document.querySelector('#searchForm').addEventListener('submit',e=>{e.preventDefault();render();document.querySelector('#catalog').scrollIntoView()});
document.querySelector('#sortSelect').addEventListener('change',render);
document.querySelectorAll('.chip').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;render()}));
document.querySelectorAll('.quick a[data-filter]').forEach(a=>a.addEventListener('click',()=>{activeFilter=a.dataset.filter;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.dataset.filter===activeFilter));render()}));
grid.addEventListener('click',e=>{const b=e.target.closest('.fav-btn');if(b){e.stopPropagation();const rawId=b.dataset.id,id=/^\d+$/.test(rawId)?+rawId:rawId;saved.has(id)?saved.delete(id):saved.add(id);localStorage.setItem('vkluche-favs',JSON.stringify([...saved]));render();toast(saved.has(id)?'Добавлено в избранное':'Удалено из избранного');return}const card=e.target.closest('.car-card');if(card){const visible=filtered(),index=[...grid.children].indexOf(card);openDetail(visible[index]);renderAuction(visible[index])}});
document.querySelectorAll('.view-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.view-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');grid.classList.toggle('list-view',b.dataset.view==='list')}));
document.querySelector('#resetBtn').addEventListener('click',()=>{activeFilter='all';document.querySelector('#searchForm').reset();document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));render()});
document.querySelector('#loadMore').addEventListener('click',()=>toast('Вы посмотрели все свежие объявления'));
const modal=document.querySelector('#modal');let wizardStep=0,uploadedPhotos=[],uploadedDocuments=[];const listingForm=document.querySelector('#listingForm');
let carModels={
  'Audi':['A3','A4','A5','A6','A7','A8','Q3','Q5','Q7','Q8'],
  'BMW':['1 серия','3 серия','5 серия','7 серия','X1','X3','X5','X6','X7'],
  'Chery':['Arrizo 8','Tiggo 4 Pro','Tiggo 7 Pro Max','Tiggo 8 Pro Max'],
  'EXEED':['LX','TXL','RX','VX'],
  'Geely':['Coolray','Atlas','Monjaro','Emgrand','Okavango'],
  'Haval':['Jolion','F7','F7x','Dargo','M6','H9'],
  'Hyundai':['Solaris','Elantra','Sonata','Creta','Tucson','Santa Fe','Palisade'],
  'Kia':['Rio','Cerato','K5','Ceed','Seltos','Sportage','Sorento','Carnival'],
  'LADA':['Granta','Vesta','Niva Legend','Niva Travel','Largus','Aura'],
  'Lexus':['ES','IS','LS','NX','RX','GX','LX'],
  'Mercedes-Benz':['A-Класс','C-Класс','E-Класс','S-Класс','CLA','GLA','GLC','GLE','GLS'],
  'Mitsubishi':['ASX','Eclipse Cross','Outlander','Pajero Sport','L200'],
  'Nissan':['Almera','Qashqai','X-Trail','Murano','Pathfinder','Patrol'],
  'Porsche':['718','911','Panamera','Macan','Cayenne','Taycan'],
  'Renault':['Logan','Sandero','Duster','Kaptur','Arkana','Koleos'],
  'Skoda':['Rapid','Octavia','Superb','Karoq','Kodiaq'],
  'Tesla':['Model 3','Model S','Model X','Model Y','Cybertruck'],
  'Toyota':['Corolla','Camry','C-HR','RAV4','Highlander','Land Cruiser Prado','Land Cruiser 300'],
  'Volkswagen':['Polo','Golf','Jetta','Passat','Taos','Tiguan','Touareg'],
  'Volvo':['S60','S90','V60','XC40','XC60','XC90']
  ,'Changan':['Alsvin','Eado Plus','Lamore','UNI-K','UNI-T','UNI-V','CS35 Plus','CS55 Plus','CS75 Plus','CS95']
  ,'GAC':['Empow','GS3','GS5','GS8','M8']
  ,'Hongqi':['H5','H9','E-HS9','HS3','HS5','HS7']
  ,'JAC':['J7','JS3','JS4','JS6','T8','T9']
  ,'Jaecoo':['J7','J8']
  ,'Jetour':['Dashing','X50','X70','X70 Plus','X90 Plus','T1','T2']
  ,'Li Auto':['L6','L7','L8','L9','Mega']
  ,'Moskvich':['3','3e','6','8']
  ,'Omoda':['C5','C7','S5','S5 GT']
  ,'Sollers':['Argo','Atlant','ST6','ST8']
  ,'Tank':['300','400','500','700']
  ,'Voyah':['Dream','Free','Passion']
  ,'Zeekr':['001','007','009','7X','Mix','X']
};
const builtInCarModels=carModels;
const brandSelect=document.querySelector('#carBrand'),modelSelect=document.querySelector('#carModel'),customBrandField=document.querySelector('#customBrandField'),customModelField=document.querySelector('#customModelField'),customBrand=document.querySelector('#customBrand'),customModel=document.querySelector('#customModel');
const otherValue='__other__';
function checkboxOptions(name,items){return items.map(item=>`<label><input type="checkbox" name="${name}" value="${escapeHtml(item.value)}"${item.checked?' checked':''}><span>${escapeHtml(item.label)}</span></label>`).join('')}
function fillFilterCities(){const selected=new Set(checkedValues('filterCity')),cities=[...new Set(cars.map(car=>car.city).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ru'));document.querySelector('#filterCityOptions').innerHTML=checkboxOptions('filterCity',cities.map(city=>({value:city,label:city,checked:selected.has(city)})))}
function fillBrands(){const brands=Object.keys(carModels).sort((a,b)=>a.localeCompare(b,'ru'));brandSelect.innerHTML=`<option value="">Выберите марку</option>${brands.map(brand=>`<option value="${brand}">${brand}</option>`).join('')}<option value="${otherValue}">Другое</option>`;brandSelect.disabled=false;const selected=new Set(checkedValues('filterBrand'));document.querySelector('#filterBrandOptions').innerHTML=checkboxOptions('filterBrand',brands.map(brand=>({value:brand,label:brand,checked:selected.has(brand)})))}
function toggleCustomField(field,input,show){field.hidden=!show;input.required=show;if(!show)input.value=''}
brandSelect.addEventListener('change',()=>{const isOther=brandSelect.value===otherValue,models=carModels[brandSelect.value]||[];toggleCustomField(customBrandField,customBrand,isOther);toggleCustomField(customModelField,customModel,isOther);modelSelect.innerHTML=isOther?'<option value="__other__">Другое</option>':models.length?`<option value="">Выберите модель</option>${models.map(model=>`<option value="${model}">${model}</option>`).join('')}<option value="${otherValue}">Другое</option>`:'<option value="">Сначала выберите марку</option>';modelSelect.disabled=!isOther&&!models.length});
modelSelect.addEventListener('change',()=>toggleCustomField(customModelField,customModel,modelSelect.value===otherValue));
function fillFilterModels(){const brands=checkedValues('filterBrand'),selected=new Set(checkedValues('filterModel')),items=brands.flatMap(brand=>(carModels[brand]||[]).map(model=>({value:`${brand}|||${model}`,label:brands.length>1?`${brand} — ${model}`:model,checked:selected.has(`${brand}|||${model}`)})));const menu=document.querySelector('#filterModelOptions'),button=menu.previousElementSibling;menu.innerHTML=items.length?checkboxOptions('filterModel',items):'<div class="multi-dropdown-menu-empty">Сначала выберите одну или несколько марок</div>';button.disabled=!items.length;if(!items.length){button.textContent='Сначала выберите марку';button.closest('.multi-dropdown').classList.remove('active')}updateDropdownLabels()}
function updateDropdownLabels(){document.querySelectorAll('.multi-dropdown').forEach(dropdown=>{const button=dropdown.querySelector('[data-dropdown-button]'),selected=[...dropdown.querySelectorAll('input:checked')],range=[...dropdown.querySelectorAll('.dropdown-range input')],rangeActive=range.some(input=>input.value!=='');if(button.disabled)return;if(rangeActive){const format=value=>['mileage','price'].includes(button.dataset.rangeLabel)?new Intl.NumberFormat('ru-RU').format(+value):value,from=range[0].value,to=range[1].value,suffix=button.dataset.rangeLabel==='mileage'?' км':button.dataset.rangeLabel==='price'?' ₽':'';button.textContent=`${from&&to?`${format(from)}–${format(to)}`:from?`от ${format(from)}`:`до ${format(to)}`}${suffix}`}else button.textContent=!selected.length?button.dataset.placeholder:selected.length===1?selected[0].nextElementSibling.textContent:`Выбрано: ${selected.length}`;dropdown.classList.toggle('active',rangeActive||selected.length>0)})}
function updateFilterPreview(){const active=filterForm.querySelectorAll('input:checked').length+[...filterForm.querySelectorAll('.dropdown-range input')].filter(input=>input.value!=='').length;document.querySelector('#filterCount').textContent=active||'';const total=filtered().length;document.querySelector('#filterPreviewCount').textContent=`${total} ${total===1?'автомобиль':total>1&&total<5?'автомобиля':'автомобилей'}`;updateDropdownLabels()}
function closeFilters(){filterPanel.classList.remove('open');filterBackdrop.classList.remove('open');document.querySelectorAll('.multi-dropdown.open').forEach(item=>item.classList.remove('open'));if(innerWidth<=650)document.body.style.overflow=''}
document.querySelector('#filterToggle').addEventListener('click',()=>{filterPanel.classList.toggle('open');filterBackdrop.classList.toggle('open',filterPanel.classList.contains('open')&&innerWidth<=650);if(innerWidth<=650)document.body.style.overflow=filterPanel.classList.contains('open')?'hidden':'';updateFilterPreview()});
document.querySelector('#filterClose').addEventListener('click',closeFilters);filterBackdrop.addEventListener('click',closeFilters);
filterForm.addEventListener('click',event=>{const button=event.target.closest('[data-dropdown-button]');if(!button||button.disabled)return;const dropdown=button.closest('.multi-dropdown'),open=!dropdown.classList.contains('open');document.querySelectorAll('.multi-dropdown.open').forEach(item=>item.classList.remove('open'));dropdown.classList.toggle('open',open)});
document.addEventListener('click',event=>{if(!event.target.closest('.multi-dropdown'))document.querySelectorAll('.multi-dropdown.open').forEach(item=>item.classList.remove('open'))});
filterForm.addEventListener('input',event=>{if(event.target.closest('.dropdown-range')&&event.target.value!=='')event.target.closest('.multi-dropdown').querySelectorAll('input[type="checkbox"]').forEach(input=>input.checked=false);updateFilterPreview()});
filterForm.addEventListener('change',event=>{if(event.target.name==='filterBrand')fillFilterModels();if(event.target.type==='checkbox'&&event.target.checked)event.target.closest('.multi-dropdown')?.querySelectorAll('.dropdown-range input').forEach(input=>input.value='');updateFilterPreview()});
filterForm.addEventListener('submit',event=>{event.preventDefault();const ranges=[['#filterPriceFrom','#filterPriceTo','цена'],['#filterYearFrom','#filterYearTo','год'],['#filterMileageFrom','#filterMileageTo','пробег']];for(const[fromSelector,toSelector,label]of ranges){const from=document.querySelector(fromSelector).value,to=document.querySelector(toSelector).value;if(from!==''&&to!==''&&+from>+to)return toast(`Проверьте диапазон: ${label} «от» больше «до»`)}render();closeFilters();document.querySelector('#catalog').scrollIntoView({behavior:'smooth'});toast(`Найдено: ${filtered().length}`)});
document.querySelector('#filterReset').addEventListener('click',()=>{filterForm.reset();fillFilterModels();updateFilterPreview();render()});
async function loadCarModels(){try{const response=await fetch('car-models.json');if(!response.ok)throw new Error('Не удалось загрузить справочник');const catalog=await response.json();carModels={...catalog};Object.entries(builtInCarModels).forEach(([brand,models])=>{carModels[brand]=[...new Set([...(carModels[brand]||[]),...models])].sort((a,b)=>a.localeCompare(b,'ru'))})}catch(error){console.warn(`${error.message}. Используется сокращённый встроенный список.`)}fillBrands()}
loadCarModels();
document.querySelector('.wizard-step[data-step="1"] .form-grid').insertAdjacentHTML('afterbegin','<label>Тип двигателя<select name="engineType"><option value="petrol">Бензин</option><option value="diesel">Дизель</option><option value="hybrid">Гибрид</option><option value="electric">Электромотор</option><option value="gas">Газ</option></select></label>');
const lastStep=document.querySelector('.wizard-step[data-step="3"]');lastStep.querySelector('p').insertAdjacentHTML('afterend','<div class="sale-mode"><button type="button" class="sale-mode-btn active" data-sale-mode="fixed">Обычная продажа</button><button type="button" class="sale-mode-btn" data-sale-mode="auction">⚡ Продать через аукцион</button></div><input type="hidden" name="saleMode" value="fixed"><div class="auction-settings" id="auctionSettings" hidden><div class="form-grid"><label>Резервная цена, ₽<input name="reservePrice" type="number" min="0" placeholder="Минимальная цена"></label><label>Продолжительность<select name="auctionDuration"><option value="2">2 часа</option><option value="6">6 часов</option><option value="12">12 часов</option><option value="24" selected>24 часа</option><option value="48">48 часов</option></select></label><label>Минимальный шаг<select name="bidStep"><option value="5000">5 000 ₽</option><option value="10000" selected>10 000 ₽</option><option value="25000">25 000 ₽</option><option value="50000">50 000 ₽</option></select></label><label class="auction-check"><input name="autoExtend" type="checkbox" checked> Продлевать торги на 5 минут при поздней ставке</label></div></div>');
document.querySelectorAll('.sale-mode-btn').forEach(button=>button.addEventListener('click',()=>{const auction=button.dataset.saleMode==='auction';document.querySelectorAll('.sale-mode-btn').forEach(item=>item.classList.toggle('active',item===button));listingForm.elements.saleMode.value=button.dataset.saleMode;document.querySelector('#auctionSettings').hidden=!auction;document.querySelector('#priceHint').textContent=auction?'Это будет стартовая цена аукциона':'Укажите стоимость автомобиля'}));
function showWizardStep(step){wizardStep=step;document.querySelectorAll('.wizard-step').forEach((x,i)=>x.classList.toggle('active',i===step));document.querySelectorAll('.wizard-progress i').forEach((x,i)=>x.classList.toggle('done',i<=step));document.querySelector('#stepLabel').textContent=`Шаг ${step+1} из 4`;document.querySelector('#wizardBack').style.visibility=step?'visible':'hidden';document.querySelector('#wizardNext').textContent=step===3?'Опубликовать':'Продолжить →'}
function openWizard(authenticated=false){if(!authenticated&&window.vklucheAuth&&!window.vklucheAuth.require(()=>openWizard(true)))return;modal.classList.add('open');document.body.style.overflow='hidden';listingForm.style.display='block';document.querySelector('#publishSuccess').style.display='none';showWizardStep(0)}
function closeWizard(){modal.classList.remove('open');document.body.style.overflow=''}
document.querySelectorAll('.open-modal').forEach(b=>b.addEventListener('click',openWizard));document.querySelector('.modal-close').addEventListener('click',closeWizard);document.querySelector('#modal .modal-backdrop').addEventListener('click',closeWizard);
document.querySelector('#wizardBack').addEventListener('click',()=>showWizardStep(Math.max(0,wizardStep-1)));document.querySelector('#wizardNext').addEventListener('click',()=>{const step=document.querySelector(`.wizard-step[data-step="${wizardStep}"]`),required=[...step.querySelectorAll('[required]')];if(!required.every(x=>x.reportValidity()))return;if(wizardStep<3){showWizardStep(wizardStep+1);return}publishListing()});
function publishListing(){
  const d=Object.fromEntries(new FormData(listingForm)),brand=brandSelect.value===otherValue?d.customBrand.trim():brandSelect.value,model=modelSelect.value===otherValue?d.customModel.trim():modelSelect.value,img=uploadedPhotos[0]||'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1000&q=85';
  const auction=d.saleMode==='auction'?{status:'active',startPrice:+d.price,reservePrice:+d.reservePrice||0,bidStep:+d.bidStep,endsAt:Date.now()+(+d.auctionDuration*60*60*1000),autoExtend:d.autoExtend==='on',bids:[]}:null;
  const car={id:Date.now(),name:`${brand} ${model}`,price:+d.price,year:+d.year,km:+d.km?`${new Intl.NumberFormat('ru-RU').format(+d.km)} км`:'Новый',engine:d.volume?`${d.volume} л / ${d.power||'—'} л.с.`:'Двигатель не указан',city:d.city,date:'только что',type:[d.condition,d.body==='Кроссовер'?'suv':'',d.engineType==='electric'?'electric':''].filter(Boolean),badge:auction?'Аукцион':'Новое объявление',img,auction,details:{brand,model,body:d.body,condition:d.condition,engineType:d.engineType,gearbox:d.gearbox,drive:d.drive,color:d.color,owners:d.owners,description:d.description,seller:d.seller,phone:d.phone,documents:[...uploadedDocuments]}};
  const own=JSON.parse(localStorage.getItem('vkluche-listings')||'[]');own.unshift(car);localStorage.setItem('vkluche-listings',JSON.stringify(own));cars.unshift(car);listingForm.style.display='none';document.querySelector('#publishSuccess').style.display='block';document.querySelector('#publishSuccess h3').textContent=auction?'Аукцион запущен!':'Объявление опубликовано!';render();renderAuctionSection();document.querySelector('#favCount').textContent=saved.size;window.lastPublished=car;
}
document.querySelector('#viewPublished').addEventListener('click',()=>{closeWizard();document.querySelector('#catalog').scrollIntoView();setTimeout(()=>{openDetail(window.lastPublished);renderAuction(window.lastPublished)},350)});
const feedModal=document.querySelector('#feedModal'),feedForm=document.querySelector('#feedForm'),feedFile=document.querySelector('#feedFile'),feedUrl=document.querySelector('#feedUrl'),feedReport=document.querySelector('#feedReport');
function openFeed(){feedModal.classList.add('open');document.body.style.overflow='hidden';feedReport.className='feed-report';feedReport.textContent='';loadFeedSources()}
function closeFeed(){feedModal.classList.remove('open');document.body.style.overflow=''}
document.querySelectorAll('.open-feed').forEach(button=>button.addEventListener('click',openFeed));document.querySelector('#feedModal .modal-close').addEventListener('click',closeFeed);document.querySelector('#feedModal .modal-backdrop').addEventListener('click',closeFeed);document.querySelector('.feed-cancel').addEventListener('click',closeFeed);
feedFile.addEventListener('change',()=>{document.querySelector('#feedFileName').textContent=feedFile.files[0]?.name||'Выберите файл с объявлениями';if(feedFile.files.length)feedUrl.value=''});
function feedText(ad,name){return ad.querySelector(name)?.textContent.trim()||''}
function feedImages(ad){return [...ad.querySelectorAll('Images > Image')].map(image=>image.getAttribute('url')||image.textContent.trim()).filter(Boolean)}
function feedCar(ad){
  const externalId=feedText(ad,'Id'),make=feedText(ad,'Make'),model=feedText(ad,'Model'),price=Number(feedText(ad,'Price')),year=Number(feedText(ad,'Year'));
  if(!externalId||!make||!model||!price||!year)throw new Error(`Объявление ${externalId||'без Id'}: обязательны Id, Make, Model, Year и Price`);
  const mileage=Number(feedText(ad,'Kilometrage')||feedText(ad,'Mileage')),power=feedText(ad,'Power'),volume=feedText(ad,'EngineSize'),images=feedImages(ad),condition=feedText(ad,'Condition').toLowerCase(),body=feedText(ad,'BodyType'),address=feedText(ad,'City')||feedText(ad,'Address')||feedText(ad,'Region')||'Город не указан';
  const engineType=feedText(ad,'EngineType')||feedText(ad,'FuelType');
  return{id:`avito:${externalId}`,externalId,source:'avito-feed',name:`${make} ${model}`,price,year,km:mileage?`${new Intl.NumberFormat('ru-RU').format(mileage)} км`:'Новый',engine:volume?`${volume} л / ${power||'—'} л.с.`:power?`${power} л.с.`:'Двигатель не указан',city:address,date:'из фида',type:[condition.includes('нов')?'new':'used',body.toLowerCase().includes('внедорож')||body.toLowerCase().includes('кроссов')?'suv':'',/элект|electric|ev/i.test(engineType)?'electric':''].filter(Boolean),badge:'Автозагрузка',img:images[0]||'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1000&q=85',details:{brand:make,model,engineType,gearbox:feedText(ad,'Transmission'),drive:feedText(ad,'DriveType'),color:feedText(ad,'Color'),description:feedText(ad,'Description'),seller:feedText(ad,'ManagerName')||feedText(ad,'ContactName'),phone:feedText(ad,'ContactPhone'),images}};
}
function importFeedXml(xmlText){const xml=new DOMParser().parseFromString(xmlText,'application/xml');if(xml.querySelector('parsererror'))throw new Error('XML-файл повреждён или имеет неверный формат');const ads=[...xml.querySelectorAll('Ads > Ad')];if(!ads.length)throw new Error('В фиде не найдены элементы Ads → Ad');const own=JSON.parse(localStorage.getItem('vkluche-listings')||'[]'),errors=[];let added=0,updated=0;ads.forEach(ad=>{try{const car=feedCar(ad),ownIndex=own.findIndex(item=>item.source==='avito-feed'&&String(item.id)===String(car.id)),carsIndex=cars.findIndex(item=>item.source==='avito-feed'&&String(item.id)===String(car.id));if(ownIndex>=0){own[ownIndex]=car;updated++}else{own.push(car);added++}if(carsIndex>=0)cars[carsIndex]=car;else cars.unshift(car)}catch(error){errors.push(error.message)}});localStorage.setItem('vkluche-listings',JSON.stringify(own));render();return{total:ads.length,added,updated,errors}}
feedForm.addEventListener('submit',async event=>{event.preventDefault();const button=document.querySelector('#importFeed');button.disabled=true;button.textContent='Загрузка…';try{let xmlText;if(feedFile.files[0])xmlText=await feedFile.files[0].text();else if(feedUrl.value.trim()){const response=await fetch(feedUrl.value.trim());if(!response.ok)throw new Error(`Сервер фида ответил с кодом ${response.status}`);xmlText=await response.text()}else throw new Error('Выберите XML-файл или укажите ссылку на фид');const result=importFeedXml(xmlText);feedReport.className=`feed-report ${result.errors.length===result.total?'error':'success'}`;feedReport.textContent=`Обработано: ${result.total}. Добавлено: ${result.added}, обновлено: ${result.updated}, ошибок: ${result.errors.length}. ${result.errors.slice(0,3).join(' ')}`;if(result.added||result.updated)document.querySelector('#catalog').scrollIntoView()}catch(error){feedReport.className='feed-report error';feedReport.textContent=`Не удалось загрузить фид: ${error.message}`}finally{button.disabled=false;button.textContent='Загрузить объявления'}});
const autoFeedForm=document.querySelector('#autoFeedForm'),feedSources=document.querySelector('#feedSources'),autoFeedNotice=document.querySelector('#autoFeedNotice');
async function adminContext(){const client=window.vklucheAuth?.getClient(),user=window.vklucheAuth?.getUser();if(!client||!user)return null;const{data}=await client.from('profiles').select('role').eq('id',user.id).maybeSingle();return data?.role==='admin'?{client,user}:null}
async function loadFeedSources(){feedSources.innerHTML='';autoFeedForm.classList.remove('allowed');autoFeedNotice.style.display='block';const context=await adminContext();if(!context){autoFeedNotice.textContent=window.vklucheAuth?.getUser()?'Управление фидами доступно только администратору.':'Войдите как администратор, чтобы управлять источниками.';return}autoFeedForm.classList.add('allowed');autoFeedNotice.style.display='none';const{data,error}=await context.client.from('feed_sources').select('*').order('created_at',{ascending:false});if(error){autoFeedNotice.style.display='block';autoFeedNotice.textContent=`Не удалось загрузить источники: ${error.message}`;return}feedSources.innerHTML=data.length?data.map(source=>`<div class="feed-source"><span><b>${escapeHtml(source.name)}</b><small>${source.interval_minutes} мин · ${source.last_run_at?`последняя проверка ${new Date(source.last_run_at).toLocaleString('ru-RU')}`:'ещё не запускался'}</small><small class="feed-source-status ${source.last_status||''}">${source.last_status==='success'?'Загружен успешно':source.last_error?escapeHtml(source.last_error):'Ожидает запуска'}</small></span><button type="button" data-sync-feed="${source.id}">Загрузить сейчас</button></div>`).join(''):'<div class="auto-feed-login">Автоматических источников пока нет.</div>'}
autoFeedForm.addEventListener('submit',async event=>{event.preventDefault();const context=await adminContext();if(!context)return window.vklucheAuth?.require(()=>openFeed());const values=new FormData(autoFeedForm),button=event.submitter;button.disabled=true;button.textContent='Добавление…';const{error}=await context.client.from('feed_sources').insert({name:values.get('name').trim(),url:values.get('url').trim(),interval_minutes:+values.get('interval'),missing_threshold:+values.get('threshold'),created_by:context.user.id});button.disabled=false;button.textContent='Добавить автоматический фид';if(error)return toast(`Не удалось добавить: ${error.message}`);autoFeedForm.reset();toast('Автоматический фид добавлен');loadFeedSources()});
feedSources.addEventListener('click',async event=>{const button=event.target.closest('[data-sync-feed]');if(!button)return;const context=await adminContext();if(!context)return toast('Нужны права администратора');button.disabled=true;button.textContent='Загрузка…';const{data,error}=await context.client.functions.invoke('import-feeds',{body:{sourceId:button.dataset.syncFeed}});button.disabled=false;button.textContent='Загрузить сейчас';if(error||data?.results?.[0]?.error)toast(`Ошибка импорта: ${data?.results?.[0]?.error||error.message}`);else{toast(`Импортировано: ${data.results[0].total}`);await loadRemoteListings();render()}loadFeedSources()});
document.querySelector('.sticky-card .finance-note').insertAdjacentHTML('afterend','<section class="auction-box" id="auctionBox"><div class="auction-head"><span>⚡ ВКЛЮЧЕ Аукцион</span><b id="auctionTimer"></b></div><div class="auction-stats"><div><small>Лучшая ставка</small><b id="auctionBest"></b></div><div><small>Предложений</small><b id="auctionBidCount"></b></div></div><form id="bidForm"><label>Ваше предложение<input id="bidAmount" type="number" min="1" required></label><label>Комментарий<input id="bidComment" maxlength="80" placeholder="Готов приехать сегодня"></label><button class="contact-btn" type="submit">Сделать предложение</button></form><div class="seller-auction"><b>Выбор продавца</b><small>Демо-режим: выберите подходящего покупателя.</small><div id="auctionBids"></div></div></section>');
document.querySelector('.auction-head>span').innerHTML='⚡ <span class="brand-inline compact"><i>В</i><span>КЛЮЧЕ</span></span> Аукцион';
const auctionBox=document.querySelector('#auctionBox'),bidForm=document.querySelector('#bidForm');
function auctionBest(auction){return Math.max(auction.startPrice,...auction.bids.map(bid=>bid.amount))}
function auctionLeft(endsAt){const left=Math.max(0,endsAt-Date.now()),hours=Math.floor(left/3600000),minutes=Math.floor(left%3600000/60000),seconds=Math.floor(left%60000/1000);return `${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`}
function renderAuctionSection(){const active=cars.filter(car=>car.auction?.status==='active'&&car.auction.endsAt>Date.now());auctionGrid.innerHTML=active.map(car=>`<article class="auction-card" data-auction-car="${escapeHtml(car.id)}"><div class="auction-card-image"><img src="${car.img}" alt="${escapeHtml(car.name)}"><span>⚡ Аукцион</span><b data-auction-countdown="${car.auction.endsAt}">${auctionLeft(car.auction.endsAt)}</b></div><div class="auction-card-body"><h3>${escapeHtml(car.name)}</h3><div class="auction-card-price"><span>Лучшая ставка</span><strong>${money(auctionBest(car.auction))}</strong></div><div class="auction-card-meta"><span>${car.year} · ${car.km}</span><span>${car.auction.bids.length} предложений</span></div><button type="button">Участвовать в торгах →</button></div></article>`).join('');auctionGrid.style.display=active.length?'grid':'none';auctionEmpty.style.display=active.length?'none':'flex'}
auctionGrid.addEventListener('click',event=>{const card=event.target.closest('[data-auction-car]');if(!card)return;const car=cars.find(item=>String(item.id)===card.dataset.auctionCar);if(car){openDetail(car);renderAuction(car)}});
function persistAuctionCar(car){const own=JSON.parse(localStorage.getItem('vkluche-listings')||'[]'),index=own.findIndex(item=>String(item.id)===String(car.id));if(index>=0){own[index]=car;localStorage.setItem('vkluche-listings',JSON.stringify(own))}const overrides=JSON.parse(localStorage.getItem('vkluche-auction-overrides')||'{}');overrides[car.id]={auction:car.auction,price:car.price,badge:car.badge};localStorage.setItem('vkluche-auction-overrides',JSON.stringify(overrides))}
function renderAuction(car){
  const auction=car.auction;document.querySelector('#mobilePrimaryAction').textContent=auction?'Сделать предложение':'Позвонить продавцу';document.querySelector('#startAuction').style.display=auction?'none':'block';auctionBox.style.display=auction?'block':'none';detail.classList.toggle('auction-active',Boolean(auction));document.querySelector('.finance-note').style.display=auction?'none':'block';
  if(!auction)return;
  if(auction.status==='active'&&Date.now()>=auction.endsAt){auction.status='awaiting_seller';persistAuctionCar(car)}
  const best=auctionBest(auction),active=auction.status==='active';document.querySelector('#detailPrice').textContent=money(best);document.querySelector('#auctionBest').textContent=money(best);document.querySelector('#auctionBidCount').textContent=auction.bids.length;document.querySelector('#auctionTimer').textContent=active?auctionLeft(auction.endsAt):auction.status==='winner_selected'?'Победитель выбран':'Торги завершены';document.querySelector('#bidAmount').min=best+auction.bidStep;document.querySelector('#bidAmount').placeholder=new Intl.NumberFormat('ru-RU').format(best+auction.bidStep);bidForm.style.display=active?'grid':'none';
  const bids=[...auction.bids].sort((a,b)=>b.amount-a.amount);document.querySelector('#auctionBids').innerHTML=bids.length?bids.map(bid=>`<div class="auction-bid ${auction.winnerId===bid.id?'winner':''}"><span><b>${escapeHtml(bid.buyer)}</b><small>${bid.rating} ★ · ${escapeHtml(bid.comment||'Без комментария')}</small></span><strong>${money(bid.amount)}</strong>${auction.status!=='winner_selected'?`<button type="button" data-winner="${escapeHtml(bid.id)}">Выбрать</button>`:' '}</div>`).join(''):'<p class="no-bids">Пока нет предложений</p>';
}
bidForm.addEventListener('submit',event=>{event.preventDefault();if(!currentCar?.auction)return;if(window.vklucheAuth&&!window.vklucheAuth.require(()=>{document.querySelector('#bidAmount').focus();toast('Теперь можно сделать предложение')}))return;const auction=currentCar.auction,amount=+document.querySelector('#bidAmount').value,best=auctionBest(auction);if(auction.status!=='active'||Date.now()>=auction.endsAt){auction.status='awaiting_seller';renderAuction(currentCar);renderAuctionSection();return toast('Торги уже завершены')}if(amount<best+auction.bidStep)return toast(`Минимальная ставка — ${money(best+auction.bidStep)}`);const authUser=window.vklucheAuth?.getUser(),buyer=authUser?.user_metadata?.name||authUser?.email?.split('@')[0]||'Покупатель ВКЛЮЧЕ';auction.bids.push({id:`bid-${Date.now()}`,userId:authUser?.id,buyer,amount,comment:document.querySelector('#bidComment').value.trim(),rating:5,createdAt:Date.now()});if(auction.autoExtend&&auction.endsAt-Date.now()<5*60*1000)auction.endsAt+=5*60*1000;currentCar.price=amount;bidForm.reset();persistAuctionCar(currentCar);renderAuction(currentCar);render();renderAuctionSection();toast('Предложение принято')});
document.querySelector('#auctionBids').addEventListener('click',event=>{const button=event.target.closest('[data-winner]');if(!button||!currentCar?.auction)return;const bid=currentCar.auction.bids.find(item=>item.id===button.dataset.winner);currentCar.auction.status='winner_selected';currentCar.auction.winnerId=bid.id;currentCar.auction.winner=bid;currentCar.price=bid.amount;currentCar.badge='Победитель выбран';persistAuctionCar(currentCar);renderAuction(currentCar);render();renderAuctionSection();toast(`${bid.buyer} выбран победителем`)});
setInterval(()=>{if(currentCar?.auction&&detail.classList.contains('open'))renderAuction(currentCar);let expired=false;document.querySelectorAll('[data-auction-countdown]').forEach(timer=>{timer.textContent=auctionLeft(+timer.dataset.auctionCountdown);if(+timer.dataset.auctionCountdown<=Date.now())expired=true});if(expired)renderAuctionSection()},1000);
const photoInput=document.querySelector('#photoInput'),photoUpload=document.querySelector('#photoUpload'),preview=document.querySelector('#uploadPreview');function readPhotos(files){[...files].slice(0,10-uploadedPhotos.length).forEach(file=>{if(!file.type.startsWith('image/'))return;const reader=new FileReader();reader.onload=()=>{uploadedPhotos.push(reader.result);renderUploads()};reader.readAsDataURL(file)})}function renderUploads(){preview.innerHTML=uploadedPhotos.map((src,i)=>`<div><img src="${src}" alt="Фото автомобиля"><button type="button" data-remove-photo="${i}">×</button></div>`).join('')}photoInput.addEventListener('change',()=>readPhotos(photoInput.files));preview.addEventListener('click',e=>{const b=e.target.closest('[data-remove-photo]');if(b){uploadedPhotos.splice(+b.dataset.removePhoto,1);renderUploads()}});['dragenter','dragover'].forEach(n=>photoUpload.addEventListener(n,e=>{e.preventDefault();photoUpload.classList.add('drag')}));['dragleave','drop'].forEach(n=>photoUpload.addEventListener(n,e=>{e.preventDefault();photoUpload.classList.remove('drag')}));photoUpload.addEventListener('drop',e=>readPhotos(e.dataTransfer.files));document.querySelector('[name="price"]').addEventListener('input',e=>document.querySelector('#priceHint').textContent=e.target.value?`Покупатель увидит: ${money(+e.target.value)}`:'Укажите стоимость автомобиля');
const documentInput=document.querySelector('#documentInput'),documentPreview=document.querySelector('#documentPreview');function renderDocuments(){documentPreview.innerHTML=uploadedDocuments.map((document,index)=>`<div><span>📎</span><b>${escapeHtml(document.name)}</b><small>${Math.ceil(document.size/1024)} КБ</small><button type="button" data-remove-document="${index}" aria-label="Удалить">×</button></div>`).join('')}documentInput.addEventListener('change',()=>{const files=[...documentInput.files].slice(0,3-uploadedDocuments.length),currentSize=uploadedDocuments.reduce((sum,item)=>sum+item.size,0);files.forEach(file=>{if(currentSize+files.reduce((sum,item)=>sum+item.size,0)>4*1024*1024)return toast('Общий размер документов не должен превышать 4 МБ');const reader=new FileReader();reader.onload=()=>{uploadedDocuments.push({name:file.name,size:file.size,type:file.type,url:reader.result});renderDocuments()};reader.readAsDataURL(file)});documentInput.value=''});documentPreview.addEventListener('click',event=>{const button=event.target.closest('[data-remove-document]');if(!button)return;uploadedDocuments.splice(+button.dataset.removeDocument,1);renderDocuments()});
document.querySelector('#menuBtn').addEventListener('click',()=>document.querySelector('#navLinks').classList.toggle('open'));
function toast(text){const t=document.querySelector('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
document.querySelector('.sticky-card .aside-fav').insertAdjacentHTML('beforebegin','<button class="start-auction-btn" id="startAuction" type="button">⚡ Выставить на аукцион</button>');
document.body.insertAdjacentHTML('beforeend','<div class="modal auction-start-modal" id="auctionStartModal" role="dialog" aria-modal="true" aria-labelledby="auctionStartTitle"><div class="modal-backdrop" data-auction-start-close></div><div class="modal-card auction-start-card"><button class="modal-close" type="button" data-auction-start-close aria-label="Закрыть">×</button><span class="eyebrow blue">ЗАПУСК ТОРГОВ</span><h2 id="auctionStartTitle">Выставить автомобиль на аукцион</h2><p id="auctionStartCar"></p><form id="auctionStartForm"><div class="form-grid"><label>Стартовая цена, ₽ *<input name="startPrice" type="number" min="1" required></label><label>Резервная цена, ₽<input name="reservePrice" type="number" min="0" placeholder="Минимальная цена продажи"></label><label>Продолжительность<select name="duration"><option value="2">2 часа</option><option value="6">6 часов</option><option value="12">12 часов</option><option value="24" selected>24 часа</option><option value="48">48 часов</option></select></label><label>Минимальный шаг<select name="bidStep"><option value="5000">5 000 ₽</option><option value="10000" selected>10 000 ₽</option><option value="25000">25 000 ₽</option><option value="50000">50 000 ₽</option></select></label></div><label class="auction-check"><input name="autoExtend" type="checkbox" checked> Продлевать торги на 5 минут при поздней ставке</label><button class="primary-btn" type="submit">Запустить аукцион</button></form></div></div>');
let currentCar=null,currentPhoto=0,currentPhotos=[];const detail=document.querySelector('#carDetail');
function openDetail(car){currentCar=car;currentPhotos=[car.img,...extraPhotos];currentPhoto=0;const d=car.details||{},seller=d.seller||'Авто Эксперт',documents=d.documents||[];document.querySelector('#detailTitle').textContent=car.name;document.querySelector('#detailPrice').textContent=money(car.price);document.querySelector('#mobilePrice').innerHTML=`${car.name}<br>${money(car.price)}`;document.querySelector('#monthlyPrice').textContent=money(Math.round(car.price/60));document.querySelector('#detailDate').textContent=`Объявление · ${car.date} · ${car.city}`;document.querySelector('#detailSpecs').innerHTML=[['Год выпуска',car.year],['Пробег',car.km],['Тип двигателя',engineTypeLabels[carEngineType(car)]],['Двигатель',car.engine],['Коробка',d.gearbox||'Автомат'],['Привод',d.drive||(car.type.includes('suv')?'Полный':'Передний')],['Кузов',d.body||(car.type.includes('suv')?'Кроссовер':'Седан')],['Цвет',d.color||'Чёрный'],['Владельцев',d.owners||'1 владелец']].map(x=>`<div class="spec"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');document.querySelector('#detailDescription').textContent=d.description||`Автомобиль в отличном состоянии. Бережная эксплуатация, своевременное обслуживание и полный комплект документов.\n\nОригинальный пробег, без серьёзных ДТП. Два комплекта ключей. Возможна проверка в любом выбранном вами сервисе. Торг после осмотра.`;document.querySelector('.seller b').textContent=seller;document.querySelector('#locationSellerName').textContent=seller;document.querySelector('#locationSellerAvatar').textContent=seller.charAt(0).toUpperCase();document.querySelector('#showPhone').textContent='Показать телефон';document.querySelector('#mapCity').textContent=car.city;const documentsSection=document.querySelector('#documentsSection');documentsSection.style.display=documents.length?'block':'none';document.querySelector('#detailDocuments').innerHTML=documents.map(document=>`<a class="vehicle-document" href="${document.url}" ${String(document.url).startsWith('data:')?`download="${escapeHtml(document.name)}"`:'target="_blank" rel="noopener"'}><span>${document.type?.includes('pdf')?'PDF':'ФАЙЛ'}</span><span><b>${escapeHtml(document.name)}</b><small>Открыть документ →</small></span></a>`).join('');updateGallery();updateDetailFav();detail.classList.add('open');document.body.style.overflow='hidden'}
const auctionStartModal=document.querySelector('#auctionStartModal'),auctionStartForm=document.querySelector('#auctionStartForm');
function closeAuctionStart(){auctionStartModal.classList.remove('open');document.body.style.overflow=detail.classList.contains('open')?'hidden':''}
document.querySelector('#startAuction').addEventListener('click',()=>{if(!currentCar||currentCar.auction)return;if(window.vklucheAuth&&!window.vklucheAuth.require(()=>document.querySelector('#startAuction').click()))return;document.querySelector('#auctionStartCar').textContent=currentCar.name;auctionStartForm.elements.startPrice.value=currentCar.price;auctionStartModal.classList.add('open')});
document.querySelectorAll('[data-auction-start-close]').forEach(button=>button.addEventListener('click',closeAuctionStart));
auctionStartForm.addEventListener('submit',event=>{event.preventDefault();if(!currentCar)return;const values=new FormData(auctionStartForm),startPrice=+values.get('startPrice'),reservePrice=+values.get('reservePrice')||0;if(reservePrice&&reservePrice<startPrice)return toast('Резервная цена должна быть не ниже стартовой');currentCar.auction={status:'active',startPrice,reservePrice,bidStep:+values.get('bidStep'),endsAt:Date.now()+(+values.get('duration')*60*60*1000),autoExtend:values.get('autoExtend')==='on',bids:[]};currentCar.price=startPrice;currentCar.badge='Аукцион';persistAuctionCar(currentCar);closeAuctionStart();renderAuction(currentCar);renderAuctionSection();render();toast('Аукцион запущен')});
function updateGallery(){document.querySelector('#detailImage').src=currentPhotos[currentPhoto];document.querySelector('#detailImage').alt=currentCar.name;document.querySelector('#photoCount').textContent=`${currentPhoto+1} / ${currentPhotos.length}`;document.querySelector('#galleryThumbs').innerHTML=currentPhotos.map((p,i)=>`<button class="${i===currentPhoto?'active':''}" data-photo="${i}"><img src="${p}" alt="Фото ${i+1}"></button>`).join('')}
function closeDetail(){detail.classList.remove('open');document.body.style.overflow=''}
document.querySelectorAll('[data-detail-close]').forEach(b=>b.addEventListener('click',closeDetail));document.querySelector('#prevPhoto').addEventListener('click',()=>{currentPhoto=(currentPhoto-1+currentPhotos.length)%currentPhotos.length;updateGallery()});document.querySelector('#nextPhoto').addEventListener('click',()=>{currentPhoto=(currentPhoto+1)%currentPhotos.length;updateGallery()});document.querySelector('#galleryThumbs').addEventListener('click',e=>{const b=e.target.closest('[data-photo]');if(b){currentPhoto=+b.dataset.photo;updateGallery()}});
function updateDetailFav(){const on=saved.has(currentCar.id),b=document.querySelector('#detailFav');b.textContent=on?'♥ В избранном':'♡ Добавить в избранное';b.classList.toggle('saved',on);const mobile=document.querySelector('#mobileFavorite');mobile.textContent=on?'♥':'♡';mobile.classList.toggle('saved',on)}
document.querySelector('#detailFav').addEventListener('click',()=>{saved.has(currentCar.id)?saved.delete(currentCar.id):saved.add(currentCar.id);localStorage.setItem('vkluche-favs',JSON.stringify([...saved]));updateDetailFav();render()});document.querySelector('#showPhone').addEventListener('click',e=>e.target.textContent=currentCar.details?.phone||'+7 927 555-18-42');document.querySelector('#sendMessage').addEventListener('click',()=>toast('Чат с продавцом открыт'));document.querySelector('#shareCar').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);toast('Ссылка скопирована')}catch{toast('Ссылка готова к отправке')}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDetail();closeWizard()}if(detail.classList.contains('open')&&e.key==='ArrowRight')document.querySelector('#nextPhoto').click();if(detail.classList.contains('open')&&e.key==='ArrowLeft')document.querySelector('#prevPhoto').click()});
const sellerProfileModal=document.querySelector('#sellerProfileModal');function openSellerProfile(){if(!currentCar)return;const seller=currentCar.details?.seller||'Авто Эксперт',initial=seller.charAt(0).toUpperCase();document.querySelector('#sellerProfileTitle').textContent=seller;document.querySelector('#sellerProfileAvatar').textContent=initial;document.querySelector('#sellerListingCount').textContent=cars.filter(car=>(car.details?.seller||'Авто Эксперт')===seller).length;sellerProfileModal.classList.add('open')}function closeSellerProfile(){sellerProfileModal.classList.remove('open')}document.querySelector('#sellerProfileLink').addEventListener('click',openSellerProfile);document.querySelectorAll('[data-seller-profile-close]').forEach(button=>button.addEventListener('click',closeSellerProfile));document.querySelector('#profileMessage').addEventListener('click',()=>{closeSellerProfile();toast('Чат с продавцом открыт')});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeSellerProfile()});
document.querySelector('#mobileFavorite').addEventListener('click',()=>document.querySelector('#detailFav').click());
document.querySelector('#mobileMessage').addEventListener('click',()=>document.querySelector('#sendMessage').click());
document.querySelector('#mobilePrimaryAction').addEventListener('click',event=>{if(currentCar?.auction){document.querySelector('#auctionBox').scrollIntoView({behavior:'smooth',block:'start'});document.querySelector('#bidAmount').focus()}else{event.currentTarget.textContent=currentCar?.details?.phone||'+7 927 555-18-42'}});
document.querySelectorAll('#navLinks a,#navLinks button').forEach(item=>item.addEventListener('click',()=>document.querySelector('#navLinks').classList.remove('open')));
async function loadRemoteListings(){const client=window.vklucheAuth?.getClient();if(!client)return;const{data,error}=await client.from('listings').select('data').eq('active',true).order('updated_at',{ascending:false});if(error){console.warn(`Каталог Supabase пока недоступен: ${error.message}`);return}for(let i=cars.length-1;i>=0;i--)if(cars[i].source==='automatic-feed')cars.splice(i,1);cars.unshift(...data.map(row=>row.data));fillFilterCities();render();renderAuctionSection()}
fillFilterCities();render();renderAuctionSection();loadRemoteListings();
