(()=>{
  const parts=[['front_bumper','Передний бампер'],['hood','Капот'],['front_left_fender','Переднее левое крыло'],['front_right_fender','Переднее правое крыло'],['front_left_door','Передняя левая дверь'],['front_right_door','Передняя правая дверь'],['rear_left_door','Задняя левая дверь'],['rear_right_door','Задняя правая дверь'],['left_pillar','Левая стойка и боковина'],['right_pillar','Правая стойка и боковина'],['left_sill','Левый порог'],['right_sill','Правый порог'],['rear_left_fender','Заднее левое крыло'],['rear_right_fender','Заднее правое крыло'],['roof','Крыша'],['trunk_lid','Крышка багажника'],['rear_bumper','Задний бампер']];
  const labels=Object.fromEntries(parts),explicitFactory=text=>/(полностью|кузов)\s+(?:в\s+)?(?:заводском|родном)\s+(?:лакокрасочном\s+)?покрытии|кузов\s+в\s+родном\s+окрасе|без\s+окрасов/i.test(text||''),genericPaint=text=>/(?:окрашенн|вторичн\w*\s+окрас|косметическ\w*\s+окрас)/i.test(text||'');
  let state={known:false,factoryPaint:false,paintedParts:[],source:'seller',note:''};
  function normalized(value,description=''){if(value&&typeof value==='object')return{known:Boolean(value.known),factoryPaint:Boolean(value.factoryPaint),paintedParts:Array.isArray(value.paintedParts)?value.paintedParts.filter(key=>labels[key]):[],source:value.source||'seller',note:value.note||''};if(explicitFactory(description))return{known:true,factoryPaint:true,paintedParts:[],source:'feed',note:'В фиде указано заводское лакокрасочное покрытие'};if(genericPaint(description))return{known:true,factoryPaint:false,paintedParts:[],source:'feed',note:'Фид сообщает об окрашенных элементах, но не называет конкретные детали'};return{known:false,factoryPaint:false,paintedParts:[],source:'feed',note:'В источнике нет данных об окрашенных элементах'}}
  const zone=(key,shape,interactive)=>`<g class="body-zone" data-body-zone="${key}" role="${interactive?'button':'img'}" aria-label="${labels[key]}"${interactive?' tabindex="0"':''}><title>${labels[key]}</title>${shape}</g>`;
  function diagram(interactive){return`<svg viewBox="0 0 760 540" role="img" aria-label="Плоская развёртка кузова автомобиля"><text class="unfolded-title" x="380" y="22">Развёртка кузова</text><path class="fold-line" d="M286 164H474M286 356H474"/>${zone('front_bumper','<path d="M316 34Q380 17 444 34L452 58Q380 47 308 58Z"/><text x="380" y="43">1</text>',interactive)}${zone('hood','<path d="M310 64Q380 49 450 64L438 158Q380 146 322 158Z"/><text x="380" y="111">2</text>',interactive)}${zone('roof','<path d="M318 166Q380 146 442 166L450 348Q380 370 310 348Z"/><text x="380" y="260">15</text>',interactive)}${zone('trunk_lid','<path d="M316 362Q380 350 444 362L452 430Q380 448 308 430Z"/><text x="380" y="399">16</text>',interactive)}${zone('rear_bumper','<path d="M308 438Q380 451 452 438L444 478Q380 498 316 478Z"/><text x="380" y="470">17</text>',interactive)}${sideWing('left',interactive)}${sideWing('right',interactive)}</svg>`}
  function sideWing(side,interactive){const right=side==='right',suffix=right?'right':'left',x=right?484:40,mirror=right?'':' transform="translate(280 0) scale(-1 1)"',nums=right?[4,6,8,10,12,14]:[3,5,7,9,11,13];return`<g${mirror}><path class="side-outline" d="M${x} 165L${x+34} 120L${x+105} 102L${x+168} 112L${x+216} 162L${x+230} 432L${x+196} 462L${x+30} 462L${x+4} 426Z"/>${zone(`front_${suffix}_fender`,`<path d="M${x} 166L${x+34} 122L${x+80} 109L${x+83} 196L${x+28} 210L${x+4} 194Z"/><text x="${x+39}" y="169">${nums[0]}</text>`,interactive)}${zone(`front_${suffix}_door`,`<path d="M${x+88} 110L${x+147} 108V278H${x+87}Z"/><text x="${x+117}" y="198">${nums[1]}</text>`,interactive)}${zone(`rear_${suffix}_door`,`<path d="M${x+153} 112L${x+196} 157L${x+205} 278H${x+153}Z"/><text x="${x+178}" y="201">${nums[2]}</text>`,interactive)}${zone(`${suffix}_pillar`,`<path d="M${x+81} 106L${x+105} 98L${x+170} 106L${x+204} 151L${x+193} 161L${x+164} 124H${x+104}L${x+88} 194L${x+78} 192Z"/><text x="${x+140}" y="116">${nums[3]}</text>`,interactive)}${zone(`${suffix}_sill`,`<path d="M${x+28} 404H${x+207}L${x+201} 450H${x+34}Z"/><text x="${x+117}" y="435">${nums[4]}</text>`,interactive)}${zone(`rear_${suffix}_fender`,`<path d="M${x+29} 286H${x+205}L${x+225} 426L${x+197} 399L${x+171} 314H${x+68}L${x+35} 399L${x+8} 423Z"/><text x="${x+117}" y="357">${nums[5]}</text>`,interactive)}</g>`}
  function zones(interactive){return`<div class="body-paint-layout"><div class="body-paint-map${interactive?'':' readonly'}">${diagram(interactive)}<div class="body-paint-legend"><span><i></i> Без отметки</span><span><i></i> Окрашено</span></div></div><aside class="body-paint-parts-list" aria-label="Список элементов кузова"><b>Элементы кузова</b>${parts.map(([key,label],index)=>`<button type="button" data-body-zone="${key}"${interactive?'':' tabindex="-1"'}><i>${index+1}</i><span>${label}</span><em>Окрашено</em></button>`).join('')}</aside></div>`}
  function summary(){if(!state.known)return'<span class="warning">Нет подтверждённых данных о состоянии ЛКП</span>';if(state.factoryPaint)return'<span class="clean">✓ Заявлен заводской окрас кузова</span>';if(!state.paintedParts.length)return`<span class="warning">${state.note||'Окрасы заявлены, конкретные элементы не указаны'}</span>`;return state.paintedParts.map(key=>`<span>${labels[key]}</span>`).join('')}
  function paint(container){container.querySelectorAll('[data-body-zone]').forEach(item=>item.classList.toggle('painted',state.paintedParts.includes(item.dataset.bodyZone)));const box=container.querySelector('.body-paint-summary');if(box)box.innerHTML=summary()}
  function toggle(event){const mode=event.target.closest('[data-paint-mode]')?.dataset.paintMode,zoneKey=event.target.closest('[data-body-zone]')?.dataset.bodyZone;if(mode){state.known=mode!=='unknown';state.factoryPaint=mode==='factory';if(mode!=='painted')state.paintedParts=[];state.source='seller';state.note=''}if(zoneKey){state.known=true;state.factoryPaint=false;state.source='seller';state.note='';state.paintedParts=state.paintedParts.includes(zoneKey)?state.paintedParts.filter(key=>key!==zoneKey):[...state.paintedParts,zoneKey]}renderEditor()}
  function injectEditor(){const target=document.querySelector('.wizard-step[data-step="1"] .equipment-editor');if(!target||document.querySelector('#bodyPaintEditor'))return;target.insertAdjacentHTML('beforebegin',`<section class="body-paint-editor" id="bodyPaintEditor"><div class="body-paint-head"><div><h4>Карта окрашенных элементов</h4><p>Выберите деталь на развёртке автомобиля или в списке справа.</p></div></div><div class="body-paint-modes"><button type="button" data-paint-mode="unknown">Не знаю</button><button type="button" data-paint-mode="factory">В заводском окрасе</button><button type="button" data-paint-mode="painted">Есть окрашенные элементы</button></div>${zones(true)}<div class="body-paint-summary"></div></section>`);const editor=document.querySelector('#bodyPaintEditor');editor.addEventListener('click',toggle);editor.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.closest('[data-body-zone]')){event.preventDefault();toggle(event)}});renderEditor()}
  function renderEditor(){const editor=document.querySelector('#bodyPaintEditor');if(!editor)return;const mode=!state.known?'unknown':state.factoryPaint?'factory':'painted';editor.querySelectorAll('[data-paint-mode]').forEach(button=>button.classList.toggle('active',button.dataset.paintMode===mode));paint(editor)}
  function reset(value,description=''){state=normalized(value,description);renderEditor()}function value(){return{known:state.known,factoryPaint:state.factoryPaint,paintedParts:[...state.paintedParts],source:'seller',note:state.note}}
  function show(car){const d=car?.details||{};state=normalized(d.bodyPaint,d.description);let section=document.querySelector('#bodyPaintDetail');if(!section){section=document.createElement('section');section.id='bodyPaintDetail';section.className='detail-section body-paint-card';document.querySelector('#detailSpecs')?.closest('.detail-section')?.after(section)}const source=state.source==='feed'?'Данные из фида':state.source==='seller'?'Указано продавцом':'Нет источника';section.innerHTML=`<div class="body-paint-head"><div><h2>Карта окрашенных элементов</h2><p>Развёртка кузова и список заявленных окрасов.</p></div><span class="body-paint-source">${source}</span></div>${zones(false)}<div class="body-paint-summary"></div>`;paint(section)}
  injectEditor();window.vklucheBodyPaint={reset,value,show,normalized};const originalFill=window.fillEditForm;if(originalFill)window.fillEditForm=car=>{originalFill(car);reset(car?.details?.bodyPaint,car?.details?.description)};const originalOpen=window.openDetail;if(originalOpen)window.openDetail=car=>{originalOpen(car);show(car)};document.querySelectorAll('.open-modal').forEach(button=>button.addEventListener('click',()=>reset(null,'')));
})();
