(()=>{
  const parts=[['front_bumper','Передний бампер','wide'],['hood','Капот','center'],['front_left_fender','Переднее левое крыло','left'],['front_right_fender','Переднее правое крыло','right'],['front_left_door','Передняя левая дверь','left'],['front_right_door','Передняя правая дверь','right'],['rear_left_door','Задняя левая дверь','left'],['rear_right_door','Задняя правая дверь','right'],['left_pillar','Левая стойка и боковина','left'],['right_pillar','Правая стойка и боковина','right'],['left_sill','Левый порог','left'],['right_sill','Правый порог','right'],['rear_left_fender','Заднее левое крыло','left'],['rear_right_fender','Заднее правое крыло','right'],['roof','Крыша','center'],['rear_bumper','Задний бампер','wide']];
  const labels=Object.fromEntries(parts.map(([key,label])=>[key,label]));let state={known:false,factoryPaint:false,paintedParts:[],source:'seller',note:''};
  const explicitFactory=text=>/(полностью|кузов)\s+(?:в\s+)?(?:заводском|родном)\s+(?:лакокрасочном\s+)?покрытии|кузов\s+в\s+родном\s+окрасе|без\s+окрасов/i.test(text||'');
  const genericPaint=text=>/(?:окрашенн|вторичн\w*\s+окрас|косметическ\w*\s+окрас)/i.test(text||'');
  function normalized(value,description=''){if(value&&typeof value==='object')return{known:Boolean(value.known),factoryPaint:Boolean(value.factoryPaint),paintedParts:Array.isArray(value.paintedParts)?value.paintedParts.filter(key=>labels[key]):[],source:value.source||'seller',note:value.note||''};if(explicitFactory(description))return{known:true,factoryPaint:true,paintedParts:[],source:'feed',note:'В фиде указано заводское лакокрасочное покрытие'};if(genericPaint(description))return{known:true,factoryPaint:false,paintedParts:[],source:'feed',note:'Фид сообщает об окрашенных элементах, но не называет конкретные детали'};return{known:false,factoryPaint:false,paintedParts:[],source:'feed',note:'В источнике нет данных об окрашенных элементах'}}
  const zoneShapes={
    front_bumper:'<path d="M110 42 Q180 15 250 42 L242 72 Q180 58 118 72Z"/><text x="180" y="49">Передний бампер</text>',
    hood:'<path d="M122 78 Q180 63 238 78 L226 178 Q180 164 134 178Z"/><text x="180" y="123">Капот</text>',
    front_left_fender:'<path d="M93 77 Q108 68 122 78 L134 178 L104 194 L86 151Z"/><text x="108" y="132">Крыло Л</text>',
    front_right_fender:'<path d="M238 78 Q252 68 267 77 L274 151 L256 194 L226 178Z"/><text x="252" y="132">Крыло П</text>',
    front_left_door:'<path d="M104 200 L142 184 L142 324 L96 324Z"/><text x="119" y="252">Передняя</text><text x="119" y="266">дверь Л</text>',
    front_right_door:'<path d="M218 184 L256 200 L264 324 L218 324Z"/><text x="241" y="252">Передняя</text><text x="241" y="266">дверь П</text>',
    rear_left_door:'<path d="M96 332 L142 332 L142 472 L104 456Z"/><text x="119" y="392">Задняя</text><text x="119" y="406">дверь Л</text>',
    rear_right_door:'<path d="M218 332 L264 332 L256 456 L218 472Z"/><text x="241" y="392">Задняя</text><text x="241" y="406">дверь П</text>',
    left_pillar:'<path d="M148 184 L164 170 L164 482 L148 470Z"/><text class="vertical-label" x="156" y="325">Стойка Л</text>',
    right_pillar:'<path d="M196 170 L212 184 L212 470 L196 482Z"/><text class="vertical-label" x="204" y="325">Стойка П</text>',
    left_sill:'<path d="M80 190 L96 200 L104 456 L88 476Z"/><text class="vertical-label" x="92" y="333">Порог Л</text>',
    right_sill:'<path d="M264 200 L280 190 L272 476 L256 456Z"/><text class="vertical-label" x="268" y="333">Порог П</text>',
    rear_left_fender:'<path d="M88 484 L104 464 L140 482 L130 584 L92 570Z"/><text x="113" y="526">Заднее</text><text x="113" y="540">крыло Л</text>',
    rear_right_fender:'<path d="M220 482 L256 464 L272 484 L268 570 L230 584Z"/><text x="247" y="526">Заднее</text><text x="247" y="540">крыло П</text>',
    roof:'<path d="M170 174 Q180 166 190 174 L190 480 Q180 492 170 480Z"/><text class="vertical-label" x="180" y="330">Крыша</text>',
    rear_bumper:'<path d="M130 590 Q180 606 230 590 L247 631 Q180 654 113 631Z"/><text x="180" y="622">Задний бампер</text>'
  };
  const zones=interactive=>`<div class="body-paint-map${interactive?'':' readonly'}"><svg viewBox="0 0 360 680" role="img" aria-label="Схема кузова автомобиля"><path class="car-contour" d="M112 30 Q180 3 248 30 Q278 57 284 132 L291 176 L290 495 Q286 578 252 640 Q180 674 108 640 Q74 578 70 495 L69 176 L76 132 Q82 57 112 30Z"/><g class="car-wheels"><rect x="56" y="120" width="22" height="92" rx="10"/><rect x="282" y="120" width="22" height="92" rx="10"/><rect x="56" y="474" width="22" height="92" rx="10"/><rect x="282" y="474" width="22" height="92" rx="10"/></g>${parts.map(([key,label])=>`<g class="body-zone" data-body-zone="${key}" role="${interactive?'button':'img'}" aria-label="${label}"${interactive?' tabindex="0"':''}><title>${label}</title>${zoneShapes[key]}</g>`).join('')}</svg><div class="body-paint-legend"><span><i></i> Заводской окрас / нет данных</span><span><i></i> Окрашенный элемент</span></div></div>`;
  function summary(){if(!state.known)return'<span class="warning">Нет подтверждённых данных о состоянии ЛКП</span>';if(state.factoryPaint)return'<span class="clean">✓ Заявлен заводской окрас кузова</span>';if(!state.paintedParts.length)return`<span class="warning">${state.note||'Окрасы заявлены, конкретные элементы не указаны'}</span>`;return state.paintedParts.map(key=>`<span>${labels[key]}</span>`).join('')}
  function paint(container){container.querySelectorAll('[data-body-zone]').forEach(button=>button.classList.toggle('painted',state.paintedParts.includes(button.dataset.bodyZone)));const box=container.querySelector('.body-paint-summary');if(box)box.innerHTML=summary()}
  function injectEditor(){const target=document.querySelector('.wizard-step[data-step="1"] .equipment-editor');if(!target||document.querySelector('#bodyPaintEditor'))return;target.insertAdjacentHTML('beforebegin',`<section class="body-paint-editor" id="bodyPaintEditor"><div class="body-paint-head"><div><h4>Карта окрашенных элементов</h4><p>Укажите фактическое состояние кузова. Нажимайте непосредственно на детали автомобиля.</p></div></div><div class="body-paint-modes"><button type="button" data-paint-mode="unknown">Не знаю</button><button type="button" data-paint-mode="factory">В заводском окрасе</button><button type="button" data-paint-mode="painted">Есть окрашенные элементы</button></div>${zones(true)}<div class="body-paint-summary"></div></section>`);const editor=document.querySelector('#bodyPaintEditor');const toggle=event=>{const mode=event.target.closest('[data-paint-mode]')?.dataset.paintMode,zone=event.target.closest('[data-body-zone]')?.dataset.bodyZone;if(mode){state.known=mode!=='unknown';state.factoryPaint=mode==='factory';if(mode!=='painted')state.paintedParts=[];state.source='seller';state.note=''}if(zone){state.known=true;state.factoryPaint=false;state.source='seller';state.note='';state.paintedParts=state.paintedParts.includes(zone)?state.paintedParts.filter(key=>key!==zone):[...state.paintedParts,zone]}renderEditor()};editor.addEventListener('click',toggle);editor.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.closest('[data-body-zone]')){event.preventDefault();toggle(event)}});renderEditor()}
  function renderEditor(){const editor=document.querySelector('#bodyPaintEditor');if(!editor)return;const mode=!state.known?'unknown':state.factoryPaint?'factory':'painted';editor.querySelectorAll('[data-paint-mode]').forEach(button=>button.classList.toggle('active',button.dataset.paintMode===mode));paint(editor)}
  function reset(value,description=''){state=normalized(value,description);renderEditor()}
  function value(){return{known:state.known,factoryPaint:state.factoryPaint,paintedParts:[...state.paintedParts],source:'seller',note:state.note}}
  function show(car){const d=car?.details||{};state=normalized(d.bodyPaint,d.description);let section=document.querySelector('#bodyPaintDetail');if(!section){section=document.createElement('section');section.id='bodyPaintDetail';section.className='detail-section body-paint-card';document.querySelector('#detailSpecs')?.closest('.detail-section')?.after(section)}const source=state.source==='feed'?'Данные из фида':state.source==='seller'?'Указано продавцом':'Нет источника';section.innerHTML=`<div class="body-paint-head"><div><h2>Карта окрашенных элементов</h2><p>Схема показывает заявленные кузовные окрасы.</p></div><span class="body-paint-source">${source}</span></div>${zones(false)}<div class="body-paint-summary"></div>`;paint(section)}
  injectEditor();window.vklucheBodyPaint={reset,value,show,normalized};
  const originalFill=window.fillEditForm;if(originalFill)window.fillEditForm=car=>{originalFill(car);reset(car?.details?.bodyPaint,car?.details?.description)};
  const originalOpen=window.openDetail;if(originalOpen)window.openDetail=car=>{originalOpen(car);show(car)};
  document.querySelectorAll('.open-modal').forEach(button=>button.addEventListener('click',()=>reset(null,'')));
})();
