(()=>{
  const parts=[['front_bumper','Передний бампер'],['hood','Капот'],['front_left_fender','Переднее левое крыло'],['front_right_fender','Переднее правое крыло'],['front_left_door','Передняя левая дверь'],['front_right_door','Передняя правая дверь'],['rear_left_door','Задняя левая дверь'],['rear_right_door','Задняя правая дверь'],['left_pillar','Левая стойка и боковина'],['right_pillar','Правая стойка и боковина'],['left_sill','Левый порог'],['right_sill','Правый порог'],['rear_left_fender','Заднее левое крыло'],['rear_right_fender','Заднее правое крыло'],['roof','Крыша'],['rear_bumper','Задний бампер']];
  const labels=Object.fromEntries(parts),explicitFactory=text=>/(полностью|кузов)\s+(?:в\s+)?(?:заводском|родном)\s+(?:лакокрасочном\s+)?покрытии|кузов\s+в\s+родном\s+окрасе|без\s+окрасов/i.test(text||''),genericPaint=text=>/(?:окрашенн|вторичн\w*\s+окрас|косметическ\w*\s+окрас)/i.test(text||'');
  let state={known:false,factoryPaint:false,paintedParts:[],source:'seller',note:''};
  function normalized(value,description=''){if(value&&typeof value==='object')return{known:Boolean(value.known),factoryPaint:Boolean(value.factoryPaint),paintedParts:Array.isArray(value.paintedParts)?value.paintedParts.filter(key=>labels[key]):[],source:value.source||'seller',note:value.note||''};if(explicitFactory(description))return{known:true,factoryPaint:true,paintedParts:[],source:'feed',note:'В фиде указано заводское лакокрасочное покрытие'};if(genericPaint(description))return{known:true,factoryPaint:false,paintedParts:[],source:'feed',note:'Фид сообщает об окрашенных элементах, но не называет конкретные детали'};return{known:false,factoryPaint:false,paintedParts:[],source:'feed',note:'В источнике нет данных об окрашенных элементах'}}
  const zone=(key,shape,interactive)=>`<g class="body-zone" data-body-zone="${key}" role="${interactive?'button':'img'}" aria-label="${labels[key]}"${interactive?' tabindex="0"':''}><title>${labels[key]}</title>${shape}</g>`;
  function diagram(interactive){return`<svg viewBox="0 0 760 540" role="img" aria-label="Развёртка кузова автомобиля"><text class="view-title" x="135" y="22">Вид сверху</text><path class="view-outline" d="M92 42Q135 20 178 42Q205 82 208 145V406Q203 470 178 506Q135 526 92 506Q67 470 62 406V145Q65 82 92 42Z"/><g class="car-wheels"><rect x="48" y="110" width="18" height="70" rx="7"/><rect x="204" y="110" width="18" height="70" rx="7"/><rect x="48" y="382" width="18" height="70" rx="7"/><rect x="204" y="382" width="18" height="70" rx="7"/></g>${zone('front_bumper','<path d="M88 44Q135 24 182 44L176 70Q135 58 94 70Z"/><text x="135" y="51">1</text>',interactive)}${zone('hood','<path d="M95 76Q135 62 175 76L169 176Q135 164 101 176Z"/><text x="135" y="124">2</text>',interactive)}${zone('roof','<path d="M101 184Q135 164 169 184V380Q135 400 101 380Z"/><text x="135" y="286">15</text>',interactive)}${zone('rear_bumper','<path d="M94 444Q135 458 176 444L184 497Q135 520 86 497Z"/><text x="135" y="486">16</text>',interactive)}${sideDiagram('left',interactive,0)}${sideDiagram('right',interactive,256)}</svg>`}
  function sideDiagram(side,interactive,offset){const right=side==='right',suffix=right?'right':'left',nums=right?[4,6,8,10,12,14]:[3,5,7,9,11,13];return`<g transform="translate(0 ${offset})"><text class="view-title" x="500" y="44">${right?'Правая':'Левая'} сторона</text><path class="side-outline" d="M294 170L326 125L412 105L507 111L566 153L680 168L700 214L684 246H294Q278 208 294 170Z"/><g class="side-wheels"><circle cx="370" cy="232" r="37"/><circle cx="620" cy="232" r="37"/></g>${zone(`front_${suffix}_fender`,`<path d="M294 171L326 127L389 112L404 177Q374 169 344 184L326 218L291 214Z"/><text x="333" y="170">${nums[0]}</text>`,interactive)}${zone(`front_${suffix}_door`,`<path d="M409 116L484 113V224H407L404 178Z"/><text x="447" y="175">${nums[1]}</text>`,interactive)}${zone(`rear_${suffix}_door`,`<path d="M490 113L548 151L568 224H490Z"/><text x="524" y="178">${nums[2]}</text>`,interactive)}${zone(`${suffix}_pillar`,`<path d="M398 112L412 105L507 111L553 151L543 158L500 124H414L404 178L394 176Z"/><text x="480" y="119">${nums[3]}</text>`,interactive)}${zone(`${suffix}_sill`,`<path d="M404 228H573L568 246H397Z"/><text x="487" y="241">${nums[4]}</text>`,interactive)}${zone(`rear_${suffix}_fender`,`<path d="M553 154L679 169L697 211L679 224H661Q648 174 606 174Q576 174 566 208Z"/><text x="647" y="189">${nums[5]}</text>`,interactive)}</g>`}
  function zones(interactive){return`<div class="body-paint-layout"><div class="body-paint-map${interactive?'':' readonly'}">${diagram(interactive)}<div class="body-paint-legend"><span><i></i> Без отметки</span><span><i></i> Окрашено</span></div></div><aside class="body-paint-parts-list" aria-label="Список элементов кузова"><b>Элементы кузова</b>${parts.map(([key,label],index)=>`<button type="button" data-body-zone="${key}"${interactive?'':' tabindex="-1"'}><i>${index+1}</i><span>${label}</span><em>Окрашено</em></button>`).join('')}</aside></div>`}
  function summary(){if(!state.known)return'<span class="warning">Нет подтверждённых данных о состоянии ЛКП</span>';if(state.factoryPaint)return'<span class="clean">✓ Заявлен заводской окрас кузова</span>';if(!state.paintedParts.length)return`<span class="warning">${state.note||'Окрасы заявлены, конкретные элементы не указаны'}</span>`;return state.paintedParts.map(key=>`<span>${labels[key]}</span>`).join('')}
  function paint(container){container.querySelectorAll('[data-body-zone]').forEach(item=>item.classList.toggle('painted',state.paintedParts.includes(item.dataset.bodyZone)));const box=container.querySelector('.body-paint-summary');if(box)box.innerHTML=summary()}
  function toggle(event){const mode=event.target.closest('[data-paint-mode]')?.dataset.paintMode,zoneKey=event.target.closest('[data-body-zone]')?.dataset.bodyZone;if(mode){state.known=mode!=='unknown';state.factoryPaint=mode==='factory';if(mode!=='painted')state.paintedParts=[];state.source='seller';state.note=''}if(zoneKey){state.known=true;state.factoryPaint=false;state.source='seller';state.note='';state.paintedParts=state.paintedParts.includes(zoneKey)?state.paintedParts.filter(key=>key!==zoneKey):[...state.paintedParts,zoneKey]}renderEditor()}
  function injectEditor(){const target=document.querySelector('.wizard-step[data-step="1"] .equipment-editor');if(!target||document.querySelector('#bodyPaintEditor'))return;target.insertAdjacentHTML('beforebegin',`<section class="body-paint-editor" id="bodyPaintEditor"><div class="body-paint-head"><div><h4>Карта окрашенных элементов</h4><p>Выберите деталь на развёртке автомобиля или в списке справа.</p></div></div><div class="body-paint-modes"><button type="button" data-paint-mode="unknown">Не знаю</button><button type="button" data-paint-mode="factory">В заводском окрасе</button><button type="button" data-paint-mode="painted">Есть окрашенные элементы</button></div>${zones(true)}<div class="body-paint-summary"></div></section>`);const editor=document.querySelector('#bodyPaintEditor');editor.addEventListener('click',toggle);editor.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.closest('[data-body-zone]')){event.preventDefault();toggle(event)}});renderEditor()}
  function renderEditor(){const editor=document.querySelector('#bodyPaintEditor');if(!editor)return;const mode=!state.known?'unknown':state.factoryPaint?'factory':'painted';editor.querySelectorAll('[data-paint-mode]').forEach(button=>button.classList.toggle('active',button.dataset.paintMode===mode));paint(editor)}
  function reset(value,description=''){state=normalized(value,description);renderEditor()}function value(){return{known:state.known,factoryPaint:state.factoryPaint,paintedParts:[...state.paintedParts],source:'seller',note:state.note}}
  function show(car){const d=car?.details||{};state=normalized(d.bodyPaint,d.description);let section=document.querySelector('#bodyPaintDetail');if(!section){section=document.createElement('section');section.id='bodyPaintDetail';section.className='detail-section body-paint-card';document.querySelector('#detailSpecs')?.closest('.detail-section')?.after(section)}const source=state.source==='feed'?'Данные из фида':state.source==='seller'?'Указано продавцом':'Нет источника';section.innerHTML=`<div class="body-paint-head"><div><h2>Карта окрашенных элементов</h2><p>Развёртка кузова и список заявленных окрасов.</p></div><span class="body-paint-source">${source}</span></div>${zones(false)}<div class="body-paint-summary"></div>`;paint(section)}
  injectEditor();window.vklucheBodyPaint={reset,value,show,normalized};const originalFill=window.fillEditForm;if(originalFill)window.fillEditForm=car=>{originalFill(car);reset(car?.details?.bodyPaint,car?.details?.description)};const originalOpen=window.openDetail;if(originalOpen)window.openDetail=car=>{originalOpen(car);show(car)};document.querySelectorAll('.open-modal').forEach(button=>button.addEventListener('click',()=>reset(null,'')));
})();
