(()=>{
  const detail=document.querySelector('#carDetail'),trust=document.querySelector('.trust-section');if(!detail||!trust)return;
  const section=document.createElement('section');section.id='conditionReport';section.className='detail-section condition-report';trust.after(section);let token=0;
  const sourceLabels={platform_specialist:'Специалист ВКЛЮЧЕ',partner_report:'Отчёт партнёра',external_registry:'Внешний реестр',provided_documents:'Предоставленные документы'},partLabels={frontBumper:'Передний бампер',hood:'Капот',roof:'Крыша',trunk:'Крышка багажника',rearBumper:'Задний бампер',leftFrontFender:'Левое переднее крыло',leftFrontDoor:'Левая передняя дверь',leftRearDoor:'Левая задняя дверь',leftRearFender:'Левое заднее крыло',rightFrontFender:'Правое переднее крыло',rightFrontDoor:'Правая передняя дверь',rightRearDoor:'Правая задняя дверь',rightRearFender:'Правое заднее крыло'};
  function row(label,value,state='neutral',source=''){return`<article class="condition-row ${state}"><i>${state==='confirmed'?'✓':state==='warning'?'!':'—'}</i><div><b>${esc(label)}</b><span>${esc(value)}</span>${source?`<small>${esc(source)}</small>`:''}</div></article>`}
  async function render(){
    const run=++token,car=window.vklucheCurrentCar?.();if(!car)return;section.innerHTML='<div class="condition-report-loading">Формируем отчёт о состоянии…</div>';
    let remote=null;const client=window.vklucheAuth?.getClient?.();if(client&&car.listingId){const result=await client.from('listings').select('organization_id,verification_status,verification_checks,moderation_note,updated_at').eq('id',car.listingId).maybeSingle();remote=result.data}
    if(run!==token)return;if(remote?.organization_id&&!car.organizationId)car.organizationId=remote.organization_id;
    const d=car.details||{},checks=remote?.verification_checks||car.verificationChecks||{},aspek=window.vklucheIsAspekVehicle?.(car),verified=(remote?.verification_status||car.verificationStatus)==='verified',source=aspek?'АСПЭК‑Авто':sourceLabels[checks.source]||'Источник не указан',paint=d.bodyPaint||{},painted=paint.paintedParts||[],damages=paint.damages||[],documents=d.documents||[],verifiedAt=checks.verified_at?new Date(checks.verified_at).toLocaleString('ru-RU'):'По данным компании';
    const checkRows=[['Осмотр кузова',aspek||checks.body],['Техническая диагностика',aspek||checks.technical],['Проверка документов',aspek||checks.legal],['Фиксация пробега',aspek||checks.mileage]].map(([label,ok])=>row(label,ok?'Проведено':'Не подтверждено',ok?'confirmed':'neutral',ok?source:'Нет результата')).join('');
    const paintText=!paint.known?'Сведения доступны в полном отчёте':paint.factoryPaint?'Заявлен заводской окрас':painted.length?`Окрашено элементов: ${painted.length}`:'Есть сведения об окрасах без перечня деталей';
    section.innerHTML=`<header class="condition-report-head"><div><span class="eyebrow blue">${aspek?'ДИАГНОСТИКА КОМПАНИИ':'ЕДИНЫЙ ОТЧЁТ'}</span><h2>Состояние автомобиля</h2><p>${aspek?'Автомобиль прошёл входной осмотр АСПЭК‑Авто.':'Проверка, кузов, повреждения и материалы в одном месте.'}</p></div><span class="condition-report-status ${aspek?'company-verified':verified?'verified':'unverified'}">${aspek?'✓ Диагностика проведена':verified?'✓ Проверено':'Не подтверждено'}</span></header>${aspek?'<div class="condition-company-note"><b>Полные результаты — по запросу</b><span>Покупателю направят диагностический отчёт и фотографии осмотра. Отметка означает проведение диагностики, а не отсутствие дефектов.</span><button type="button" data-request-company-report>Получить отчёт и фотографии</button></div>':''}<div class="condition-report-meta"><span><small>Автомобиль</small><b>${esc(car.name)}</b></span><span><small>VIN</small><b>${esc(d.vin?`${d.vin.slice(0,4)}••••••${d.vin.slice(-4)}`:'не указан')}</b></span><span><small>Дата проверки</small><b>${esc(aspek||verified?verifiedAt:'—')}</b></span></div><section><h3>${aspek?'Что проверено компанией':'Результаты независимой проверки'}</h3><div class="condition-check-grid">${checkRows}</div>${remote?.moderation_note?`<blockquote><b>Комментарий специалиста</b><span>${esc(remote.moderation_note)}</span></blockquote>`:''}</section><section><h3>Кузов и лакокрасочное покрытие</h3>${row('Окрашенные элементы',paintText,paint.factoryPaint?'confirmed':painted.length?'warning':'neutral',paint.source==='feed'?'Данные из фида':aspek?'Подробности в отчёте':'Указано продавцом')}${painted.length?`<div class="condition-tags">${painted.map(x=>`<span>${esc(partLabels[x]||x)}</span>`).join('')}</div>`:''}</section><section><h3>Заявленные повреждения</h3>${damages.length?`<div class="condition-damages">${damages.map(x=>row(partLabels[x.part]||x.part,`${x.type}${x.note?` — ${x.note}`:''}`,'warning',aspek?'Данные компании':'Указано продавцом')).join('')}</div>`:'<p class="condition-empty">Подробности и фотографии доступны в полном отчёте. Это не заменяет личный осмотр автомобиля.</p>'}</section><section><h3>Документы и материалы</h3>${documents.length?`<div class="condition-documents">${documents.map(x=>`<span><b>${esc(x.name||'Документ')}</b><small>Прикреплено продавцом</small></span>`).join('')}</div>`:'<p class="condition-empty">Дополнительные файлы пока не приложены к карточке.</p>'}</section><div class="condition-report-warning"><b>Важно</b><span>Отчёт отражает сведения, доступные на указанную дату, и не гарантирует отсутствие скрытых дефектов. Перед сделкой проведите самостоятельный осмотр.</span></div><button class="condition-print" type="button">Распечатать отчёт</button>`;
    section.querySelector('[data-request-company-report]')?.addEventListener('click',()=>document.querySelector('#historyReportButton')?.click());section.querySelector('.condition-print').onclick=()=>{document.body.classList.add('printing-condition-report');window.print();setTimeout(()=>document.body.classList.remove('printing-condition-report'),500)};
  }
  function esc(value){const div=document.createElement('div');div.textContent=value??'';return div.innerHTML}
  new MutationObserver(()=>{if(detail.classList.contains('open'))setTimeout(render,0)}).observe(detail,{attributes:true,attributeFilter:['class']});
})();
