(()=>{
  const anchor=document.querySelector('#sendMessage');if(!anchor)return;
  const button=document.createElement('button');button.type='button';button.id='openConsultation';button.className='consultation-open';button.textContent='Получить консультацию';anchor.after(button);
  document.body.insertAdjacentHTML('beforeend',`<div class="modal consultation-modal" id="consultationModal" role="dialog" aria-modal="true" aria-labelledby="consultationTitle"><div class="modal-backdrop" data-consultation-close></div><div class="modal-card consultation-card"><button class="modal-close" type="button" data-consultation-close>×</button><span class="eyebrow blue">ОДНО ОБРАЩЕНИЕ</span><h2 id="consultationTitle">Получить консультацию</h2><p id="consultationVehicle"></p><form id="consultationForm"><label>Тема<select name="type"><option value="purchase">Покупка автомобиля</option><option value="callback">Обратный звонок</option><option value="credit">Кредит</option><option value="trade_in">Trade-in</option><option value="auction">Участие в аукционе</option><option value="other">Другой вопрос</option></select></label><label>Как ответить<select name="channel"><option value="phone">Позвонить</option><option value="site">Ответить на сайте</option><option value="telegram">Telegram</option><option value="max">MAX</option></select></label><label>Телефон<input name="phone" type="tel" maxlength="30" autocomplete="tel"></label><label>Ваш вопрос<textarea name="message" required minlength="5" maxlength="1500" rows="4" placeholder="Опишите, чем вам помочь"></textarea></label><label class="consultation-consent"><input name="consent" type="checkbox" required><span>Согласен на обработку контактных данных для ответа на это обращение.</span></label><button class="primary-btn" type="submit">Отправить обращение</button></form></div></div>`);
  const modal=document.querySelector('#consultationModal'),form=document.querySelector('#consultationForm');
  function close(){modal.classList.remove('open');document.body.style.overflow=document.querySelector('#carDetail')?.classList.contains('open')?'hidden':''}
  function open(){if(!window.vklucheAuth?.require(open))return;const car=window.vklucheCurrentCar?.();form.reset();form.elements.phone.value=window.vklucheAuth.getUser()?.user_metadata?.phone||'';form.dataset.listingId=car?.listingId||'';form.dataset.vehicle=car?.name||'';document.querySelector('#consultationVehicle').textContent=car?.name||'Общий вопрос';modal.classList.add('open');document.body.style.overflow='hidden'}
  button.addEventListener('click',open);document.querySelectorAll('[data-consultation-close]').forEach(item=>item.addEventListener('click',close));
  form.addEventListener('submit',async event=>{event.preventDefault();const client=window.vklucheAuth?.getClient?.(),user=window.vklucheAuth?.getUser?.(),data=new FormData(form),channel=String(data.get('channel')),phone=String(data.get('phone')).trim();if(channel==='phone'&&!phone)return window.toast?.('Укажите телефон для обратного звонка');const submit=event.submitter;submit.disabled=true;submit.textContent='Отправляем…';const{error}=await client.from('customer_inquiries').insert({user_id:user.id,listing_id:form.dataset.listingId||null,vehicle_name:form.dataset.vehicle||null,inquiry_type:String(data.get('type')),preferred_channel:channel,phone:phone||null,message:String(data.get('message')).trim(),personal_data_consent:true});submit.disabled=false;submit.textContent='Отправить обращение';if(error)return window.toast?.(`Обращение не отправлено: ${error.message}`);close();window.toast?.('Обращение принято. Статус появится в кабинете');window.dispatchEvent(new CustomEvent('vkluche:inquiries-changed'))});
})();
