(function(){
  const articles={
    sell:{title:'Разместить автомобиль',group:'Продажа',summary:'Создание объявления вручную',steps:['Нажмите «Продать» в шапке сайта.','Выберите марку и модель, заполните характеристики и VIN.','Добавьте реальные фотографии, описание состояния и документы.','Укажите точный адрес осмотра на карте.','Проверьте цену и нажмите «Опубликовать».'],note:'После публикации автомобиль отправляется на проверку. Проверочные отметки выставляет только специалист или администратор.',action:'sell'},
    auction:{title:'Запустить аукцион',group:'Аукционы',summary:'Выставление своего автомобиля на торги',steps:['Опубликуйте автомобиль или откройте его в разделе «Продажи».','Откройте карточку и нажмите «Выставить на аукцион».','Устраните замечания в проверке готовности лота.','Укажите стартовую и резервную цены, шаг и длительность.','Выберите правило победы и круг участников, затем подтвердите запуск.'],note:'Продавец запускает аукцион только для своего автомобиля. Администратор может управлять всеми лотами.',action:'auctions'},
    bid:{title:'Принять участие в аукционе',group:'Аукционы',summary:'Ставка, продление и результат',steps:['Откройте вкладку «Идут сейчас».','Выберите лот и изучите паспорт, документы и правило определения победителя.','Введите сумму не ниже следующей минимальной ставки.','Проверьте сумму в окне подтверждения.','Если предложение выбрано, подтвердите покупку в течение 24 часов.'],note:'Ставка не отменяется во время торгов. Поздняя ставка может автоматически продлить аукцион на пять минут.',action:'auctions'},
    feed:{title:'Подключить XML-фид',group:'Профессионалам',summary:'Разовая или автоматическая загрузка склада',steps:['Создайте профиль компании, если фид относится к организации.','Откройте «Ещё» → «Загрузить фид».','Укажите постоянную HTTPS-ссылку и период обновления.','Добавленный после создания компании фид привяжется к ней автоматически.','Ранее добавленный фид передаёт организации только системный администратор.'],note:'Организация не может видеть или присваивать фиды другой компании.',action:'feed'},
    company:{title:'Настроить компанию',group:'Профессионалам',summary:'Филиалы, сотрудники и общий склад',steps:['Зарегистрируйтесь как профессиональный участник.','Откройте профиль → «Компания» и создайте организацию.','Добавьте филиалы с адресами площадок.','Добавьте зарегистрированных сотрудников и назначьте роли.','Привяжите объявления и фиды к общему складу.'],note:'Владелец и администратор управляют сотрудниками. Менеджер работает со складом и аукционами, наблюдатель имеет доступ только к просмотру.',action:'company'},
    bulk:{title:'Запустить массовые торги',group:'Профессионалам',summary:'Несколько автомобилей из общего склада',steps:['Откройте профиль компании.','В общем складе отметьте автомобили галочками.','Выберите длительность, шаг и правило победы.','Нажмите «Запустить выбранные».','Система пропустит автомобили, не прошедшие проверку готовности.'],note:'У автомобиля должны быть VIN, фотография, описание состояния и адрес осмотра.',action:'company'},
    notifications:{title:'Настроить уведомления',group:'Аккаунт',summary:'ВКЛЮЧЕ, email, Telegram и MAX',steps:['Нажмите колокольчик в шапке.','Выберите «Настроить».','Отметьте нужные каналы.','Выберите события аукциона и осмотра.','Сохраните настройки.'],note:'Внутренняя история остаётся основным источником. Telegram и MAX потребуют подключения ботов.',action:'notifications'},
    withdraw:{title:'Снять объявление',group:'Продажа',summary:'Продажа, пауза или перенос в архив',steps:['Откройте своё объявление или раздел «Продажи».','Нажмите «Снять с публикации».','Выберите причину.','Подтвердите действие.','При временном снятии объявление можно восстановить из кабинета.'],note:'Активный аукцион необходимо завершить до снятия автомобиля с публикации.',action:'seller'}
  };
  const tours={
    sell:[['.header-sell','Начните размещение','Кнопка открывает пошаговую форму объявления.'],['#modal .wizard-progress','Четыре понятных шага','Заполните автомобиль, характеристики, фото и условия продажи.'],['#wizardNext','Переходите дальше','Обязательные поля проверяются перед каждым следующим шагом.']],
    auction:[['a[href="#auctions"]','Раздел аукционов','Здесь собраны текущие, предстоящие и завершённые торги.'],['#auctionTabs','Выберите состояние','Переключайтесь между этапами проведения аукциона.'],['#auctionGrid','Откройте автомобиль','В карточке лота находятся ставка, документы и условия участия.']],
    bid:[['#auctionTabs','Найдите активные торги','Откройте вкладку «Идут сейчас».'],['#auctionGrid','Изучите лот','Нажмите на автомобиль, чтобы увидеть паспорт и сделать ставку.']],
    feed:[['.more-nav','Откройте дополнительное меню','Загрузка фида находится в разделе «Ещё».'],['.open-feed','Загрузите источник','Можно выбрать XML-файл или добавить постоянную ссылку.']],
    company:[['.profile-trigger','Откройте личный кабинет','Раздел компании доступен профессиональным участникам.'],['#dashboardTabs','Выберите «Компания»','Здесь находятся филиалы, сотрудники, склад, фиды и аналитика.']],
    notifications:[['#notificationBell','Центр уведомлений','Откройте колокольчик, чтобы увидеть историю и настройки.']]
  };
  document.body.insertAdjacentHTML('beforeend','<div class="help-shell" id="helpShell" aria-hidden="true"><div class="help-backdrop" data-help-close></div><aside class="help-panel" role="dialog" aria-modal="true" aria-labelledby="helpTitle"><div class="help-home"><div class="help-panel-head"><div><span class="eyebrow blue">ЦЕНТР ПОМОЩИ</span><h2 id="helpTitle">Чем помочь?</h2></div><button class="help-close" type="button" data-help-close>×</button></div><input class="help-search" id="helpSearch" type="search" placeholder="Найти инструкцию"><span class="help-role" id="helpRole"></span><section class="help-section"><h3>Быстрые маршруты</h3><div class="help-routes" id="helpRoutes"></div></section><section class="help-section"><h3>Все инструкции</h3><div class="help-articles" id="helpArticles"></div></section></div><article class="help-article" id="helpArticle"></article></aside></div>');
  const shell=document.querySelector('#helpShell'),home=shell.querySelector('.help-home'),article=shell.querySelector('#helpArticle'),search=shell.querySelector('#helpSearch');
  function roleInfo(){const role=window.vklucheAuth?.getRole?.()||'user',type=window.vklucheAuth?.getAccountType?.()||'private';return{role,type,label:role==='admin'?'Администратор':type==='professional'?'Профессиональный участник':'Частное лицо'}}
  function visibleKeys(){const{role,type}=roleInfo();return Object.keys(articles).filter(key=>!['feed','company','bulk'].includes(key)||type==='professional'||role==='admin')}
  function renderList(query=''){const keys=visibleKeys().filter(key=>`${articles[key].title} ${articles[key].summary} ${articles[key].group}`.toLowerCase().includes(query.toLowerCase()));document.querySelector('#helpRole').textContent=roleInfo().label;document.querySelector('#helpRoutes').innerHTML=keys.filter(key=>tours[key]).slice(0,6).map(key=>`<button class="help-route" type="button" data-help-tour="${key}"><span><b>${articles[key].title}</b><small>${articles[key].summary}</small></span><i>Показать →</i></button>`).join('');document.querySelector('#helpArticles').innerHTML=keys.length?keys.map(key=>`<button class="help-article-link" type="button" data-help-article="${key}"><span><b>${articles[key].title}</b><small>${articles[key].group} · ${articles[key].summary}</small></span><i>→</i></button>`).join(''):'<div class="help-empty">Инструкция не найдена</div>'}
  function open(){renderList();home.style.display='block';article.classList.remove('open');shell.classList.add('open');shell.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>search.focus(),250)}function close(){shell.classList.remove('open');shell.setAttribute('aria-hidden','true');document.body.style.overflow=''}
  function showArticle(key){const item=articles[key];if(!item)return;home.style.display='none';article.innerHTML=`<button class="help-article-back" type="button">← Все инструкции</button><span class="eyebrow blue">${item.group}</span><h3>${item.title}</h3><p>${item.summary}</p><ol>${item.steps.map(step=>`<li>${step}</li>`).join('')}</ol><div class="help-article-note">${item.note}</div><button class="help-article-action" type="button" data-help-action="${item.action}">Перейти и выполнить</button>`;article.classList.add('open')}
  function action(name){close();if(name==='sell')return document.querySelector('.header-sell')?.click();if(name==='auctions'){document.querySelector('#auctions')?.scrollIntoView({behavior:'smooth'});return}if(name==='feed')return document.querySelector('.open-feed')?.click();if(name==='notifications')return document.querySelector('#notificationBell')?.click();if(['company','seller'].includes(name)){window.vklucheAuth?.open?.('profile');setTimeout(()=>window.dispatchEvent(new CustomEvent('vkluche:dashboard-tab',{detail:{tab:name==='company'?'business':'seller'}})),150)}}
  let tourLayer=null,tourSteps=[],tourIndex=0;function stopTour(){tourLayer?.remove();tourLayer=null;document.querySelectorAll('.help-tour-opened').forEach(el=>el.classList.remove('help-tour-opened'))}function positionTour(){if(!tourLayer)return;const [selector,title,text]=tourSteps[tourIndex],target=document.querySelector(selector);if(!target){tourIndex++;if(tourIndex>=tourSteps.length)return stopTour();return positionTour()}target.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>{const rect=target.getBoundingClientRect(),focus=tourLayer.querySelector('.tour-focus'),card=tourLayer.querySelector('.tour-card');focus.style.cssText=`left:${Math.max(4,rect.left-5)}px;top:${Math.max(4,rect.top-5)}px;width:${Math.max(20,rect.width+10)}px;height:${Math.max(20,rect.height+10)}px`;card.style.left=`${Math.min(innerWidth-card.offsetWidth-12,Math.max(12,rect.left))}px`;card.style.top=`${Math.min(innerHeight-card.offsetHeight-12,Math.max(12,rect.bottom+12))}px`;card.querySelector('b').textContent=title;card.querySelector('p').textContent=text;card.querySelector('.tour-next').textContent=tourIndex===tourSteps.length-1?'Готово':'Далее';card.querySelector('small').textContent=`${tourIndex+1} из ${tourSteps.length}`},350)}function startTour(key){const steps=tours[key];if(!steps)return;close();if(key==='sell')document.querySelector('.header-sell')?.click();if(key==='company'){window.vklucheAuth?.open?.('profile');setTimeout(()=>window.dispatchEvent(new CustomEvent('vkluche:dashboard-tab',{detail:{tab:'business'}})),100)}tourSteps=steps;tourIndex=0;document.body.insertAdjacentHTML('beforeend','<div class="tour-layer"><div class="tour-focus"></div><div class="tour-card"><small></small><b></b><p></p><div class="tour-actions"><button class="tour-skip" type="button">Закрыть</button><button class="tour-next" type="button">Далее</button></div></div></div>');tourLayer=document.querySelector('.tour-layer');tourLayer.querySelector('.tour-skip').onclick=stopTour;tourLayer.querySelector('.tour-next').onclick=()=>{if(++tourIndex>=tourSteps.length){localStorage.setItem(`vkluche-help-tour-${key}`,'done');stopTour()}else positionTour()};setTimeout(positionTour,450)}
  function addContext(selector,text){const found=document.querySelector(selector),label=found?.matches('label')?found:found?.closest('label');if(!label||label.querySelector('.context-help'))return;const button=document.createElement('button');button.type='button';button.className='context-help';button.textContent='?';button.dataset.helpText=text;button.setAttribute('aria-label','Пояснение');label.insertBefore(button,found||null)}
  function installContext(){addContext('#auctionStartForm [name="reservePrice"]','Минимальная цена продажи. Участники её не видят. Если резерв не достигнут, аукцион завершится без сделки.');addContext('#auctionStartForm [name="bidStep"]','Минимальная сумма, на которую новая ставка должна превышать текущую.');addContext('#auctionStartForm [name="winnerMode"]','Можно автоматически выбрать максимальную ставку либо оставить решение за продавцом. Правило видно участникам заранее.');addContext('#auctionStartForm [name="participantAccess"]','Доступ можно открыть всем проверенным пользователям или только профессиональным участникам.');addContext('#auctionStartForm .auction-check','Ставка в последние пять минут переносит окончание ещё на пять минут.');addContext('#autoFeedForm [name="url"]','Постоянная HTTPS-ссылка на XML-фид. После создания компании новый источник привязывается к ней автоматически.');addContext('[data-bulk-auctions] [name="winnerMode"]','Одно правило будет применено ко всем выбранным автомобилям. Неготовые лоты система не запустит.');addContext('[data-attach-feed] [name="feedId"]','Ранее загруженный источник и его автомобили может передать компании только системный администратор.')}
  document.querySelector('#helpTrigger')?.addEventListener('click',open);shell.addEventListener('click',event=>{if(event.target.closest('[data-help-close]'))close();const link=event.target.closest('[data-help-article]');if(link)showArticle(link.dataset.helpArticle);const route=event.target.closest('[data-help-tour]');if(route)startTour(route.dataset.helpTour);if(event.target.closest('.help-article-back')){article.classList.remove('open');home.style.display='block'}const act=event.target.closest('[data-help-action]');if(act)action(act.dataset.helpAction)});search.addEventListener('input',()=>renderList(search.value));document.addEventListener('click',event=>{const button=event.target.closest('.context-help');document.querySelector('.context-popover')?.remove();if(!button)return;event.preventDefault();event.stopPropagation();const rect=button.getBoundingClientRect(),popover=document.createElement('div');popover.className='context-popover';popover.textContent=button.dataset.helpText;document.body.append(popover);popover.style.left=`${Math.min(innerWidth-popover.offsetWidth-12,Math.max(12,rect.left))}px`;popover.style.top=`${Math.min(innerHeight-popover.offsetHeight-12,rect.bottom+7)}px`});document.addEventListener('keydown',event=>{if(event.key==='Escape'){if(tourLayer)stopTour();else if(shell.classList.contains('open'))close()}});window.addEventListener('resize',()=>tourLayer&&positionTour());window.addEventListener('vkluche:profile',()=>shell.classList.contains('open')&&renderList(search.value));let contextTimer;new MutationObserver(()=>{clearTimeout(contextTimer);contextTimer=setTimeout(installContext,80)}).observe(document.querySelector('#dashboardContent'),{childList:true,subtree:true});installContext();window.vklucheHelp={open,startTour,showArticle,refresh:installContext};
})();
