(function(){
  const tours={
    buy:{prepare(){document.querySelector('#searchForm')?.scrollIntoView({behavior:'smooth'})},steps:[['#searchForm','Единый поиск','Здесь задаются основные параметры и открываются дополнительные фильтры.'],['#searchForm .search-btn','Показать автомобили','Кнопка применяет все выбранные условия и показывает число найденных вариантов.'],['#carsGrid','Каталог','Откройте карточку или нажмите сердце, чтобы сохранить автомобиль.']]},
    bid:{prepare(){document.querySelector('#auctions')?.scrollIntoView({behavior:'smooth'})},steps:[['#auctionTabs','Состояние торгов','Выберите «Идут сейчас», чтобы оставить ставку.'],['#auctionGrid','Действующие лоты','Откройте автомобиль — форма ставки находится в его подробной карточке.']]},
    sell:{prepare(){document.querySelector('.header-sell')?.click()},steps:[['.header-sell','Кнопка «Продать»','На компьютере она находится справа в шапке. На телефоне действие доступно через меню.'],['#modal .wizard-progress','Этапы объявления','Индикатор показывает текущий шаг: автомобиль, характеристики, материалы и условия.'],['#wizardNext','Кнопка продолжения','После заполнения обязательных полей переходите к следующему шагу.']]},
    auction:{prepare(){openCabinet('seller')},steps:[['[data-dashboard-tab="seller"]','Вкладка «Продажи»','Здесь находятся ваши объявления — продавать и запускать торги можно из одной карточки.'],['#dashboardContent .dashboard-row','Ваш автомобиль','Откройте нужное объявление, затем в карточке нажмите «Выставить на аукцион».']]},
    withdraw:{prepare(){openCabinet('seller')},steps:[['[data-dashboard-tab="seller"]','Вкладка «Продажи»','Откройте список своих опубликованных и архивных объявлений.'],['#dashboardContent .dashboard-row','Карточка автомобиля','Откройте автомобиль; кнопка «Снять с публикации» находится в действиях владельца.']]},
    company:{prepare(){openCabinet('business')},steps:[['[data-dashboard-tab="business"]','Вкладка «Компания»','Она появляется у профессионального участника и администратора.'],['#dashboardContent .business-heading','Профиль организации','В верхней части показана выбранная компания и ваша роль.'],['#dashboardContent [data-create-branch],#dashboardContent .business-grid','Филиалы','Здесь создаются площадки хранения и осмотра.']]},
    bulk:{prepare(){openCabinet('business')},steps:[['[data-dashboard-tab="business"]','Откройте «Компания»','Склад организации находится внутри этой вкладки личного кабинета.'],['#dashboardContent [data-bulk-auctions]','Общий склад и массовые торги','Это нужный блок. До него можно прокрутить страницу кабинета.'],['#dashboardContent .bulk-inventory','Выберите автомобили','Отметьте галочками автомобили без активных торгов.'],['#dashboardContent .bulk-settings','Запустите выбранные','Задайте длительность, шаг и правило победы, затем нажмите кнопку запуска.']]},
    feed:{prepare(){document.querySelector('.more-nav')?.setAttribute('open','')},steps:[['.more-nav','Меню «Ещё»','Откройте дополнительное меню в шапке.'],['.open-feed','Пункт «Загрузить фид»','Нажмите его, чтобы добавить файл или постоянную ссылку.']]},
    notifications:{prepare(){document.querySelector('#notificationBell')?.click()},steps:[['#notificationBell','Колокольчик','Число рядом показывает количество непрочитанных событий.'],['#notificationPanel','Панель уведомлений','Нажмите событие для перехода или «Настроить» для выбора каналов.']]},
    moderation:{prepare(){openCabinet('moderation')},steps:[['[data-dashboard-tab="moderation"]','Вкладка «Модерация»','Она видна только системному администратору.'],['#dashboardContent .verification-card','Карточка проверки','Нажмите «Начать проверку», чтобы открыть форму результата.']]}
  };
  let layer=null,current=[],index=0,topic='';
  function openCabinet(tab){window.vklucheAuth?.open?.('profile');setTimeout(()=>window.dispatchEvent(new CustomEvent('vkluche:dashboard-tab',{detail:{tab}})),100)}
  function stop(done=false){if(done&&topic)localStorage.setItem(`vkluche-help-tour-${topic}`,'done');layer?.remove();layer=null}
  function place(){if(!layer)return;const [selector,title,text]=current[index],target=document.querySelector(selector);if(!target){if(++index>=current.length)return stop();return setTimeout(place,180)}target.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>{if(!layer)return;const r=target.getBoundingClientRect(),focus=layer.querySelector('.tour-focus'),card=layer.querySelector('.tour-card');focus.style.cssText=`left:${Math.max(4,r.left-5)}px;top:${Math.max(4,r.top-5)}px;width:${Math.max(24,r.width+10)}px;height:${Math.max(24,r.height+10)}px`;card.style.left=`${Math.min(innerWidth-card.offsetWidth-12,Math.max(12,r.left))}px`;card.style.top=`${Math.min(innerHeight-card.offsetHeight-12,Math.max(12,r.bottom+12))}px`;card.querySelector('b').textContent=title;card.querySelector('p').textContent=text;card.querySelector('small').textContent=`${index+1} из ${current.length}`;card.querySelector('.tour-next').textContent=index===current.length-1?'Готово':'Далее'},350)}
  function start(key){const tour=tours[key];if(!tour)return false;topic=key;document.querySelector('[data-hclose]')?.click();tour.prepare?.();current=tour.steps;index=0;document.body.insertAdjacentHTML('beforeend','<div class="tour-layer"><div class="tour-focus"></div><div class="tour-card"><small></small><b></b><p></p><div class="tour-actions"><button class="tour-skip">Закрыть</button><button class="tour-next">Далее</button></div></div></div>');layer=document.querySelector('.tour-layer');layer.querySelector('.tour-skip').onclick=()=>stop();layer.querySelector('.tour-next').onclick=()=>{if(++index>=current.length)stop(true);else place()};setTimeout(place,650);return true}
  document.addEventListener('click',event=>{const button=event.target.closest('[data-guide]');if(!button||!tours[button.dataset.guide])return;event.preventDefault();event.stopImmediatePropagation();start(button.dataset.guide)},true);
  document.addEventListener('keydown',event=>{if(event.key==='Escape'&&layer)stop()});window.addEventListener('resize',()=>layer&&place());window.vklucheHelpTour={start};
})();
