(function(){
  const tours={
    buy:{prepare(){document.querySelector('#searchForm')?.scrollIntoView({behavior:'smooth'})},steps:[['#searchForm','Единый поиск','Задайте марку, модель и город, затем откройте дополнительные фильтры для цены, года, пробега и характеристик.'],['#searchForm .search-btn','Показать автомобили','Число на кнопке соответствует полному результату с учётом выбранных условий.'],['#carsGrid','Каталог','Откройте карточку, добавьте вариант в избранное или выберите до четырёх автомобилей для сравнения.'],['#carsGrid','Подробная проверка','В карточке изучите фотографии, комплектацию, документы, проверки, адрес и профиль продавца.'],['#carsGrid','Связь с продавцом','После проверки данных позвоните или напишите продавцу и договоритесь об осмотре.']]},
    bid:{prepare(){document.querySelector('#auctions')?.scrollIntoView({behavior:'smooth'});document.querySelector('[data-auction-tab="active"]')?.click()},steps:[['#auctionTabs','Выберите активные торги','Во вкладке «Идут сейчас» собраны лоты, по которым ещё можно сделать ставку.'],['#auctionGrid','Откройте нужный лот','На карточке видны текущая цена и время до окончания. Нажмите на автомобиль, чтобы перейти к участию.'],['#auctionBox','Паспорт и правила лота','Перед ставкой проверьте автомобиль, документы, шаг торгов и правило выбора победителя.',openFirstAuction],['#auctionBest','Текущая лучшая ставка','Следующее предложение должно быть не ниже этой суммы плюс установленный шаг аукциона.'],['#bidForm','Введите предложение','Укажите сумму и нажмите «Сделать предложение». Продавец не может делать ставки на собственный лот.'],['#bidConfirmModal','Подтвердите ставку','Проверьте сумму в отдельном окне. После подтверждения сервер запишет ставку и обновит историю.',showBidConfirmation],['#auctionBids','Следите за историей','Принятое предложение выделяется подписью «Моя ставка». Здесь же меняются лучшая цена и количество ставок.'],['#notificationBell','Узнайте, если ставку перебили','Колокольчик сообщит о новой более высокой ставке. Нажатие на уведомление вернёт вас к этому лоту.']]},
    sell:{prepare(){document.querySelector('.header-sell')?.click()},steps:[['.header-sell','Кнопка «Продать»','На компьютере она находится справа в шапке, на телефоне — внутри меню.'],['#modal .wizard-progress','VIN и основные данные','Сначала определите автомобиль по VIN, затем обязательно проверьте найденные марку, модель, год и характеристики.'],['#modal .wizard-progress','Комплектация','Выберите поколение, модификацию и комплектацию, раскройте группы оборудования и отметьте второй комплект шин или колёс.'],['#modal .wizard-progress','Материалы и адрес','Добавьте фотографии и документы, заполните цену, описание и точный адрес осмотра на карте.'],['#wizardNext','Проверка перед отправкой','Заполните обязательные поля каждого этапа и просмотрите итоговые сведения перед публикацией.']]},
    auction:{prepare(){openCabinet('seller')},steps:[['[data-dashboard-tab="seller"]','Вкладка «Продажи»','Здесь находятся ваши объявления. Продавец запускает торги только по своим автомобилям, администратор — по любым.'],['#dashboardContent .dashboard-row','Выберите опубликованный автомобиль','Откройте нужную карточку и найдите действие «Выставить на аукцион».'],['#dashboardContent .dashboard-row','Проверьте готовность','До запуска должны быть заполнены обязательные данные и устранены замечания проверки.'],['#dashboardContent .dashboard-row','Задайте условия','Укажите стартовую цену, минимальный шаг, срок, продление и правило определения победителя.'],['#dashboardContent .dashboard-row','Контролируйте результат','После запуска следите за предложениями и по окончании действуйте по заранее выбранному правилу.']]},
    withdraw:{prepare(){openCabinet('seller')},steps:[['[data-dashboard-tab="seller"]','Вкладка «Продажи»','Откройте список собственных опубликованных, приостановленных и архивных объявлений.'],['#dashboardContent .dashboard-row','Карточка автомобиля','Откройте нужный автомобиль и найдите действие «Снять с публикации».'],['#dashboardContent .dashboard-row','Причина снятия','Выберите: продано, временная пауза или другая причина — от ответа зависит новый статус.'],['#dashboardContent .dashboard-row','Восстановление','Временно снятый автомобиль остаётся в кабинете и может быть опубликован повторно.']]},
    company:{prepare(){openCabinet('business')},steps:[['[data-dashboard-tab="business"]','Вкладка «Компания»','Она доступна профессиональному участнику и администратору.'],['#dashboardContent .business-heading','Профиль организации','Проверьте выбранную компанию, реквизиты и свою роль.'],['#dashboardContent [data-create-branch],#dashboardContent .business-grid','Филиалы','Добавьте площадки хранения и осмотра с точными адресами.'],['#dashboardContent .business-grid','Сотрудники и права','Приглашайте коллег и выдавайте только необходимые полномочия.'],['#dashboardContent [data-bulk-auctions]','Общий склад','Здесь видны автомобили компании, их статусы, филиалы и действующие аукционы.']]},
    bulk:{prepare(){openCabinet('business')},steps:[['[data-dashboard-tab="business"]','Откройте «Компания»','Склад организации находится внутри этой вкладки личного кабинета.'],['#dashboardContent [data-bulk-auctions]','Общий склад и массовые торги','Это нужный блок. До него можно прокрутить страницу кабинета.'],['#dashboardContent .bulk-inventory','Выберите автомобили','Отметьте галочками автомобили без активных торгов.'],['#dashboardContent .bulk-settings','Запустите выбранные','Задайте длительность, шаг и правило победы, затем нажмите кнопку запуска.']]},
    feed:{prepare(){document.querySelector('.more-nav')?.setAttribute('open','')},steps:[['.more-nav','Меню «Ещё»','Откройте дополнительное меню в шапке. Перед загрузкой создайте профиль компании.'],['.open-feed','Пункт «Загрузить фид»','Добавьте постоянную публичную HTTPS-ссылку на XML вашей организации.'],['.open-feed','Период обновления','Настройте расписание и правило снятия автомобилей, исчезнувших из источника.'],['.open-feed','Контроль импорта','Статус, последняя попытка и причина ошибки доступны в карточке автоматического фида компании.'],['.open-feed','Повторная загрузка','После исправления источника используйте «Повторить сейчас» и проверьте склад компании.']]},
    notifications:{prepare(){document.querySelector('#notificationBell')?.click()},steps:[['#notificationBell','Колокольчик','Число рядом показывает количество непрочитанных событий.'],['#notificationPanel','Переход к событию','Нажмите уведомление, чтобы открыть связанный автомобиль или аукцион и отметить событие прочитанным.'],['#notificationPanel','Выбор событий','Через «Настроить» включите старт и окончание торгов, перебитую ставку, проверки и другие события.'],['#notificationPanel','Каналы','Выберите сайт, email, а после подключения ботов — Telegram или MAX.'],['#notificationPanel','Проверка доставки','Отправьте тестовое письмо и при необходимости изучите историю доставки.']]},
    moderation:{prepare(){openCabinet('moderation')},steps:[['[data-dashboard-tab="moderation"]','Вкладка «Модерация»','Она видна только системному администратору.'],['#dashboardContent .verification-card','Автомобиль на проверке','Откройте нужную карточку и нажмите «Начать проверку».'],['#dashboardContent .verification-card','Сверка материалов','Проверьте VIN, характеристики, фотографии, документы и диагностические файлы.'],['#dashboardContent .verification-card','Подтверждённые пункты','Отмечайте проверку только при наличии реального источника, а не со слов продавца.'],['#dashboardContent .verification-card','Решение','Сохраните результат — статус автомобиля и уведомление владельца должны обновиться.']]}
  };
  let layer=null,current=[],index=0,topic='';
  function openCabinet(tab){window.vklucheAuth?.open?.('profile');setTimeout(()=>window.dispatchEvent(new CustomEvent('vkluche:dashboard-tab',{detail:{tab}})),100)}
  function openFirstAuction(){if(document.querySelector('#carDetail.open #auctionBox'))return;document.querySelector('#auctionGrid [data-auction-car]')?.click()}
  function showBidConfirmation(){const modal=document.querySelector('#bidConfirmModal');if(!modal)return;const amount=document.querySelector('#bidAmount'),minimum=Number(amount?.min||0);if(amount&&!amount.value)amount.value=minimum;document.querySelector('#bidConfirmAmount').textContent=minimum.toLocaleString('ru-RU')+' ₽';document.querySelector('#bidConfirmNext').textContent='После подтверждения ставка появится в истории предложений.';document.querySelector('#bidConfirmRule').textContent='Это демонстрация: ставка не отправляется без вашего подтверждения.';document.querySelector('#bidParticipantStatus').textContent='Проверьте сумму перед отправкой';modal.classList.add('open')}
  function stop(done=false){if(done&&topic)localStorage.setItem(`vkluche-help-tour-${topic}`,'done');layer?.remove();layer=null;if(topic==='bid')document.querySelector('#bidConfirmModal.open [data-bid-confirm-close]')?.click()}
  function place(){if(!layer)return;const [selector,title,text,before]=current[index];before?.();setTimeout(()=>{const target=document.querySelector(selector);if(!target||target.offsetParent===null){if(++index>=current.length)return stop();return place()}target.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>{if(!layer)return;const r=target.getBoundingClientRect(),focus=layer.querySelector('.tour-focus'),card=layer.querySelector('.tour-card');focus.style.cssText=`left:${Math.max(4,r.left-5)}px;top:${Math.max(4,r.top-5)}px;width:${Math.max(24,r.width+10)}px;height:${Math.max(24,r.height+10)}px`;card.style.left=`${Math.min(innerWidth-card.offsetWidth-12,Math.max(12,r.left))}px`;card.style.top=`${Math.min(innerHeight-card.offsetHeight-12,Math.max(12,r.bottom+12))}px`;card.querySelector('b').textContent=title;card.querySelector('p').textContent=text;card.querySelector('small').textContent=`${index+1} из ${current.length}`;card.querySelector('.tour-next').textContent=index===current.length-1?'Готово':'Далее'},350)},before?180:0)}
  function start(key){const tour=tours[key];if(!tour)return false;topic=key;document.querySelector('[data-hclose]')?.click();tour.prepare?.();current=tour.steps;index=0;document.body.insertAdjacentHTML('beforeend','<div class="tour-layer"><div class="tour-focus"></div><div class="tour-card"><small></small><b></b><p></p><div class="tour-actions"><button class="tour-skip">Закрыть</button><button class="tour-next">Далее</button></div></div></div>');layer=document.querySelector('.tour-layer');layer.querySelector('.tour-skip').onclick=()=>stop();layer.querySelector('.tour-next').onclick=()=>{if(++index>=current.length)stop(true);else place()};setTimeout(place,650);return true}
  document.addEventListener('click',event=>{const button=event.target.closest('[data-guide]');if(!button||!tours[button.dataset.guide])return;if(button.dataset.guide==='bid'&&!document.querySelector('#auctionGrid [data-auction-car]'))return;event.preventDefault();event.stopImmediatePropagation();start(button.dataset.guide)},true);
  document.querySelector('.auction-rules-link')?.addEventListener('click',async event=>{event.preventDefault();await window.vklucheHelp?.open?.();window.vklucheHelp?.show?.('bid')});
  document.addEventListener('keydown',event=>{if(event.key==='Escape'&&layer)stop()});window.addEventListener('resize',()=>layer&&place());window.vklucheHelpTour={start};
})();
