(function(){
  document.body.insertAdjacentHTML('beforeend','<div class="modal" id="privacyCenter" role="dialog" aria-modal="true"><div class="modal-backdrop" data-privacy-close></div><div class="modal-card privacy-card"><button class="modal-close" type="button" data-privacy-close>×</button><span class="eyebrow blue">ПЕРСОНАЛЬНЫЕ ДАННЫЕ</span><h2>Согласия и данные</h2><p>Здесь можно проверить историю и отключить необязательную обработку.</p><div id="privacyConsentList"></div><div class="privacy-actions"><a href="legal.html#privacy" target="_blank">Открыть документы</a><button id="privacyRequest" type="button">Запросить выгрузку или удаление</button></div></div></div>');
  const modal=document.querySelector('#privacyCenter'),list=document.querySelector('#privacyConsentList'),labels={terms:'Пользовательское соглашение',personal_data:'Обработка персональных данных',privacy:'Политика персональных данных',marketing:'Новости и предложения',channel_email:'Email-уведомления',channel_telegram:'Telegram',channel_max:'MAX'};
  const close=()=>modal.classList.remove('open');document.querySelectorAll('[data-privacy-close]').forEach(x=>x.addEventListener('click',close));
  async function open(){const auth=window.vklucheAuth;if(!auth?.require(open))return;modal.classList.add('open');list.innerHTML='<p>Загружаем историю…</p>';const{data,error}=await auth.getClient().from('user_consents').select('*').order('created_at',{ascending:false});if(error){list.innerHTML=`<p>${error.message}</p>`;return}const latest=new Map();(data||[]).forEach(row=>{if(!latest.has(row.document_code))latest.set(row.document_code,row)});list.innerHTML=[...latest].map(([code,row])=>`<article class="privacy-consent-row"><span><b>${labels[code]||code}</b><small>Версия ${row.document_version} · ${new Date(row.created_at).toLocaleString('ru-RU')}</small></span><div><em class="${row.granted?'granted':'revoked'}">${row.granted?'Дано':'Отозвано'}</em>${['marketing','channel_email','channel_telegram','channel_max'].includes(code)?`<button type="button" data-consent-code="${code}" data-consent-value="${!row.granted}">${row.granted?'Отключить':'Включить'}</button>`:''}</div></article>`).join('')||'<p>История согласий пока отсутствует.</p>'}
  document.querySelector('#privacyRequest').addEventListener('click',async()=>{close();await window.vklucheHelp?.open?.();setTimeout(()=>document.querySelector('#helpShell [data-support]')?.click(),100)});
  list.addEventListener('click',async event=>{const button=event.target.closest('[data-consent-code]');if(!button)return;const code=button.dataset.consentCode,granted=button.dataset.consentValue==='true',client=window.vklucheAuth.getClient();button.disabled=true;const{error}=await client.rpc('set_optional_consent',{p_code:code,p_granted:granted,p_metadata:{source:'privacy_center'}});if(error){button.disabled=false;return window.toast?.(error.message)}if(code==='channel_email')await client.from('notification_preferences').update({email_enabled:granted,updated_at:new Date().toISOString()}).eq('user_id',window.vklucheAuth.getUser().id);window.toast?.(granted?'Согласие дано':'Согласие отозвано');open()});
  document.addEventListener('click',event=>{if(event.target.closest('[data-open-privacy]'))open()});window.vkluchePrivacy={open};
})();
