(function(){
  const grid=document.querySelector('#procurementGrid'),modal=document.querySelector('#procurementModal'),offerModal=document.querySelector('#procurementOfferModal');if(!grid)return;
  document.querySelector('#procurementForm .procurement-form-grid')?.insertAdjacentHTML('afterbegin','<label>Заявитель<select name="organizationId" id="procurementOrganization"><option value="">Личная заявка</option></select></label>');
  const money=value=>new Intl.NumberFormat('ru-RU').format(+value||0)+' ₽',esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let rows=[],tab='active',selected=null,channel=null;
  const client=()=>window.vklucheAuth?.getClient?.(),user=()=>window.vklucheAuth?.getUser?.();
  function tell(message){const toast=document.querySelector('#toast');if(!toast)return;toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
  function status(row){if(row.status==='active'&&new Date(row.ends_at)>new Date())return['Принимает предложения','active'];return[{selected:'Предложение выбрано',completed:'Завершена',cancelled:'Отменена'}[row.status]||'Завершена',row.status]}
  function remaining(date){const ms=new Date(date)-Date.now();if(ms<=0)return'срок завершён';const h=Math.ceil(ms/36e5);return h<24?`${h} ч`:`${Math.ceil(h/24)} дн.`}
  function card(row){const [label]=status(row),mine=row.buyer_id===user()?.id,active=row.status==='active'&&new Date(row.ends_at)>new Date(),best=row.best_amount?money(row.best_amount):'Пока нет предложений',offers=mine&&row.offers?.length?`<div class="procurement-offers">${row.offers.map(o=>`<article><span><b>${esc(o.vehicle_name)}</b><small>${money(o.amount)} · ${esc(o.comment||'без комментария')}</small></span>${o.selected?'<em>Выбрано</em>':active?`<button class="procurement-select" data-select-offer="${o.id}">Выбрать</button>`:''}</article>`).join('')}</div>`:'';return`<article class="procurement-card" data-request="${row.id}"><header><span class="procurement-status">${label}</span><small>${active?'ещё '+remaining(row.ends_at):new Date(row.ends_at).toLocaleDateString('ru-RU')}</small></header><div><h3>${esc(row.brand)} ${esc(row.model||'— любая модель')}</h3><p>${esc(row.notes||'Без дополнительных пожеланий')}</p></div><div class="procurement-facts"><span><small>Год</small><b>${row.year_from||'—'}–${row.year_to||'любой'}</b></span><span><small>Пробег до</small><b>${row.mileage_to?new Intl.NumberFormat('ru-RU').format(row.mileage_to)+' км':'любой'}</b></span><span><small>Бюджет до</small><b>${money(row.budget_max)}</b></span><span><small>Шаг снижения</small><b>${money(row.price_step)}</b></span></div><div class="procurement-best"><small>Лучшее предложение · ${row.offer_count||0}</small><b>${best}</b></div>${offers}<footer>${active&&!mine?'<button class="procurement-offer" data-offer>Предложить автомобиль</button>':''}${active&&mine?'<button class="procurement-cancel" data-cancel-request>Отменить заявку</button>':''}</footer></article>`}
  function render(){const uid=user()?.id,filtered=rows.filter(row=>tab==='mine'?row.buyer_id===uid:tab==='completed'?row.status!=='active'||new Date(row.ends_at)<=new Date():row.status==='active'&&new Date(row.ends_at)>new Date());grid.innerHTML=filtered.length?filtered.map(card).join(''):`<div class="procurement-empty"><b>${tab==='mine'?'У вас пока нет заявок':'Заявок в этом разделе пока нет'}</b><p>${tab==='active'?'Создайте заявку — продавцы увидят, какой автомобиль вы ищете.':'Здесь появится история обратных аукционов.'}</p></div>`}
  async function load(){const api=client();if(!api){grid.innerHTML='<div class="procurement-empty">Для заявок требуется подключение к сервису.</div>';return}const{data,error}=await api.rpc('procurement_catalog');if(error){grid.innerHTML=`<div class="procurement-empty">Заявки пока недоступны: ${esc(error.message)}</div>`;return}rows=Array.isArray(data)?data:[];render()}
  function requireAuth(action){if(window.vklucheAuth?.require?.(action))return true;return false}
  document.querySelector('#newProcurement').onclick=async()=>{if(!requireAuth(()=>document.querySelector('#newProcurement').click()))return;const organization=document.querySelector('#procurementOrganization'),{data}=await client().from('organization_members').select('organization_id,organizations(name)').eq('user_id',user().id).eq('active',true).in('member_role',['owner','administrator','manager']);organization.innerHTML='<option value="">Личная заявка</option>'+((data||[]).map(item=>`<option value="${item.organization_id}">Компания · ${esc(item.organizations?.name||'организация')}</option>`).join(''));modal.classList.add('open')};document.querySelectorAll('[data-procurement-close]').forEach(el=>el.onclick=()=>modal.classList.remove('open'));document.querySelectorAll('[data-procurement-offer-close]').forEach(el=>el.onclick=()=>offerModal.classList.remove('open'));
  document.querySelector('#procurementTabs').onclick=event=>{const button=event.target.closest('[data-procurement-tab]');if(!button)return;tab=button.dataset.procurementTab;document.querySelectorAll('[data-procurement-tab]').forEach(item=>item.classList.toggle('active',item===button));render()};
  document.querySelector('#procurementForm').onsubmit=async event=>{event.preventDefault();const form=new FormData(event.currentTarget),button=event.submitter,from=+form.get('yearFrom')||null,to=+form.get('yearTo')||null;if(from&&to&&from>to)return tell('Проверьте диапазон года');button.disabled=true;const{error}=await client().rpc('create_procurement_request',{p_brand:form.get('brand').trim(),p_model:form.get('model').trim(),p_year_from:from,p_year_to:to,p_mileage_to:+form.get('mileageTo')||null,p_budget_max:+form.get('budget'),p_price_step:+form.get('step'),p_duration_hours:+form.get('duration'),p_notes:form.get('notes').trim(),p_organization_id:form.get('organizationId')||null});button.disabled=false;if(error)return tell(error.message);event.currentTarget.reset();event.currentTarget.elements.step.value=10000;modal.classList.remove('open');tab='mine';document.querySelectorAll('[data-procurement-tab]').forEach(item=>item.classList.toggle('active',item.dataset.procurementTab==='mine'));await load();tell('Заявка опубликована')};
  async function openOffer(row){if(!requireAuth(()=>openOffer(row)))return;selected=row;const select=offerModal.querySelector('[name="listingId"]'),api=client(),uid=user().id,{data:members}=await api.from('organization_members').select('organization_id').eq('user_id',uid).eq('active',true),orgs=(members||[]).map(item=>item.organization_id),ownerFilter=[`owner_id.eq.${uid}`,...(orgs.length?[`organization_id.in.(${orgs.join(',')})`]:[])].join(','),{data,error}=await api.from('listings').select('id,data,organization_id').eq('status','published').eq('active',true).or(ownerFilter);if(error)return tell(error.message);select.innerHTML='<option value="">Выберите автомобиль</option>'+((data||[]).map(item=>`<option value="${item.id}">${esc(item.data?.name||'Автомобиль')} · ${money(item.data?.price)}</option>`).join(''));const limit=Math.max(1,row.best_amount?row.best_amount-row.price_step:row.budget_max);offerModal.querySelector('[name="amount"]').max=limit;offerModal.querySelector('[name="amount"]').value=limit;document.querySelector('#procurementOfferHint').textContent=data?.length?`Цена должна быть не выше ${money(limit)}.`:'У вас нет опубликованных автомобилей, которые можно предложить.';offerModal.classList.add('open')}
  grid.onclick=async event=>{const cardNode=event.target.closest('[data-request]'),row=rows.find(item=>item.id===cardNode?.dataset.request);if(!row)return;if(event.target.closest('[data-offer]'))return openOffer(row);const choose=event.target.closest('[data-select-offer]');if(choose){if(!confirm('Выбрать это предложение победителем?'))return;const{error}=await client().rpc('select_procurement_offer',{p_offer_id:choose.dataset.selectOffer});if(error)return tell(error.message);await load();return tell('Предложение выбрано')}if(event.target.closest('[data-cancel-request]')){if(!confirm('Отменить заявку на покупку?'))return;const{error}=await client().rpc('cancel_procurement_request',{p_request_id:row.id});if(error)return tell(error.message);await load();tell('Заявка отменена')}};
  document.querySelector('#procurementOfferForm').onsubmit=async event=>{event.preventDefault();const form=new FormData(event.currentTarget),button=event.submitter;button.disabled=true;const{error}=await client().rpc('place_procurement_offer',{p_request_id:selected.id,p_listing_id:form.get('listingId'),p_amount:+form.get('amount'),p_comment:form.get('comment').trim()});button.disabled=false;if(error)return tell(error.message);event.currentTarget.reset();offerModal.classList.remove('open');await load();tell('Предложение отправлено')};
  function realtime(){const api=client();if(!api||channel)return;channel=api.channel('vkluche-procurement').on('postgres_changes',{event:'*',schema:'public',table:'procurement_requests'},load).on('postgres_changes',{event:'*',schema:'public',table:'procurement_offers'},load).subscribe()}
  window.addEventListener('vkluche:profile',()=>{load();realtime()});window.addEventListener('vkluche:auth',load);load();setTimeout(realtime,1200);
})();
