(()=>{
  const anchor=document.querySelector('#openViewing');if(!anchor)return;
  const button=document.createElement('button');button.type='button';button.id='openReservation';button.className='reservation-open';button.textContent='Забронировать автомобиль';anchor.after(button);
  document.body.insertAdjacentHTML('beforeend',`<div class="modal reservation-modal" id="reservationModal" role="dialog" aria-modal="true" aria-labelledby="reservationTitle"><div class="modal-backdrop" data-reservation-close></div><div class="modal-card reservation-card"><button class="modal-close" type="button" data-reservation-close>×</button><span class="eyebrow blue">БЕЗ ОНЛАЙН-ОПЛАТЫ</span><h2 id="reservationTitle">Запросить бронь</h2><p id="reservationVehicle"></p><div class="reservation-note"><b>Как это работает</b><span>Продавец подтвердит или отклонит запрос. Деньги на сайте не списываются, бронь не является договором покупки.</span></div><form id="reservationForm"><label>Желаемый срок<select name="hours"><option value="2">2 часа</option><option value="4" selected>4 часа</option><option value="12">12 часов</option><option value="24">24 часа</option><option value="48">48 часов</option></select></label><label>Телефон<input name="phone" type="tel" required maxlength="30" autocomplete="tel"></label><label>Комментарий<textarea name="comment" rows="3" maxlength="700" placeholder="Например, до приезда на осмотр"></textarea></label><button class="primary-btn" type="submit">Отправить запрос на бронь</button></form></div></div>`);
  const modal=document.querySelector('#reservationModal'),form=document.querySelector('#reservationForm');
  function close(){modal.classList.remove('open');document.body.style.overflow=document.querySelector('#carDetail')?.classList.contains('open')?'hidden':''}
  function open(){if(!window.vklucheAuth?.require(open))return;const car=window.vklucheCurrentCar?.();if(!car?.listingId)return window.toast?.('Бронирование доступно только для опубликованных объявлений');form.reset();form.elements.phone.value=window.vklucheAuth.getUser()?.user_metadata?.phone||'';form.dataset.listingId=car.listingId;document.querySelector('#reservationVehicle').textContent=car.name;modal.classList.add('open');document.body.style.overflow='hidden'}
  button.addEventListener('click',open);document.querySelectorAll('[data-reservation-close]').forEach(item=>item.addEventListener('click',close));
  form.addEventListener('submit',async event=>{event.preventDefault();const client=window.vklucheAuth?.getClient?.(),user=window.vklucheAuth?.getUser?.(),data=new FormData(form),submit=event.submitter;submit.disabled=true;submit.textContent='Отправляем…';const{error}=await client.from('listing_reservations').insert({listing_id:form.dataset.listingId,buyer_id:user.id,seller_id:user.id,requested_hours:+data.get('hours'),phone:String(data.get('phone')).trim(),comment:String(data.get('comment')).trim()||null});submit.disabled=false;submit.textContent='Отправить запрос на бронь';if(error)return window.toast?.(`Бронь не создана: ${error.message}`);close();window.toast?.('Запрос на бронь отправлен продавцу');window.dispatchEvent(new CustomEvent('vkluche:reservations-changed'))});
})();
