(()=>{
  const loan=document.querySelector('#openLoanCalculator');if(!loan)return;
  const button=document.createElement('button');button.type='button';button.id='openTradeIn';button.className='trade-in-open';button.textContent='Оценить мой автомобиль в trade-in';loan.after(button);
  document.body.insertAdjacentHTML('beforeend',`<div class="modal trade-in-modal" id="tradeInModal" role="dialog" aria-modal="true" aria-labelledby="tradeInTitle"><div class="modal-backdrop" data-trade-in-close></div><div class="modal-card trade-in-card"><button class="modal-close" type="button" data-trade-in-close>×</button><span class="eyebrow blue">ПРЕДВАРИТЕЛЬНАЯ ОЦЕНКА</span><h2 id="tradeInTitle">Автомобиль в trade-in</h2><p>Укажите основные сведения. Специалист уточнит состояние и предложит осмотр.</p><div class="trade-in-target"><small>Выбранный автомобиль</small><b id="tradeInTarget">—</b></div><form id="tradeInForm"><div class="trade-in-fields"><label>Марка<input name="brand" required maxlength="60" placeholder="Toyota"></label><label>Модель<input name="model" required maxlength="80" placeholder="Camry"></label><label>Год выпуска<input name="year" type="number" min="1950" max="2100" required placeholder="2020"></label><label>Пробег, км<input name="mileage" type="number" min="0" required placeholder="75000"></label><label>Город<input name="city" required maxlength="100" placeholder="Самара"></label><label>Состояние<select name="condition"><option value="excellent">Отличное</option><option value="good" selected>Хорошее</option><option value="requires_repair">Требует ремонта</option><option value="damaged">После ДТП</option></select></label></div><label>Телефон<input name="phone" type="tel" required maxlength="30" autocomplete="tel"></label><label>Комментарий<textarea name="comment" maxlength="1000" rows="3" placeholder="Комплектация, владельцы, особенности состояния"></textarea></label><label class="trade-in-consent"><input name="consent" type="checkbox" required><span>Согласен на обработку персональных данных и связь со мной по заявке. Итоговая стоимость определяется после осмотра.</span></label><button class="primary-btn" type="submit">Получить предварительную оценку</button></form></div></div>`);
  const modal=document.querySelector('#tradeInModal'),form=document.querySelector('#tradeInForm');
  function close(){modal.classList.remove('open');document.body.style.overflow=document.querySelector('#carDetail')?.classList.contains('open')?'hidden':''}
  function open(){if(!window.vklucheAuth?.require(open))return;const car=window.vklucheCurrentCar?.(),meta=window.vklucheAuth.getUser()?.user_metadata||{};document.querySelector('#tradeInTarget').textContent=car?.name||'Автомобиль из каталога';form.reset();form.elements.phone.value=meta.phone||'';form.dataset.listingId=car?.listingId||'';form.dataset.vehicle=car?.name||'';modal.classList.add('open');document.body.style.overflow='hidden'}
  button.addEventListener('click',open);document.querySelectorAll('[data-trade-in-close]').forEach(item=>item.addEventListener('click',close));
  form.addEventListener('submit',async event=>{event.preventDefault();const client=window.vklucheAuth?.getClient?.(),user=window.vklucheAuth?.getUser?.();if(!client||!user)return;const data=new FormData(form),submit=event.submitter;submit.disabled=true;submit.textContent='Отправляем…';const{error}=await client.from('trade_in_requests').insert({user_id:user.id,target_listing_id:form.dataset.listingId||null,target_vehicle:form.dataset.vehicle||null,brand:String(data.get('brand')).trim(),model:String(data.get('model')).trim(),production_year:+data.get('year'),mileage:+data.get('mileage'),city:String(data.get('city')).trim(),condition:String(data.get('condition')),phone:String(data.get('phone')).trim(),comment:String(data.get('comment')).trim()||null,personal_data_consent:true,consent_at:new Date().toISOString()});submit.disabled=false;submit.textContent='Получить предварительную оценку';if(error)return window.toast?.(`Заявка не отправлена: ${error.message}`);close();window.toast?.('Заявка принята. Статус появится в личном кабинете');window.dispatchEvent(new CustomEvent('vkluche:trade-in-changed'))});
})();
