(()=>{
  const loan=document.querySelector('#openLoanCalculator');
  if(loan&&!document.querySelector('#openTradeIn')){const button=document.createElement('button');button.type='button';button.id='openTradeIn';button.className='trade-in-open open-trade-in';button.textContent='Оценить мой автомобиль в trade-in';loan.after(button)}
  document.body.insertAdjacentHTML('beforeend',`<div class="modal trade-in-modal" id="tradeInModal" role="dialog" aria-modal="true" aria-labelledby="tradeInTitle"><div class="modal-backdrop" data-trade-in-close></div><div class="modal-card trade-in-card"><button class="modal-close" type="button" data-trade-in-close>×</button><span class="eyebrow blue">ПРЕДВАРИТЕЛЬНАЯ ОЦЕНКА</span><h2 id="tradeInTitle">Автомобиль в trade-in</h2><p>Укажите основные сведения. Специалист уточнит состояние и предложит осмотр.</p><div class="trade-in-target"><small>Выбранный автомобиль</small><b id="tradeInTarget">—</b></div><form id="tradeInForm"><div class="trade-in-fields"><label>Марка<select name="brandChoice" required><option value="">Загружаем марки…</option></select><input name="customBrand" maxlength="60" placeholder="Введите марку" hidden></label><label>Модель<select name="modelChoice" required disabled><option value="">Сначала выберите марку</option></select><input name="customModel" maxlength="80" placeholder="Введите модель" hidden></label><label>Год выпуска<input name="year" type="number" min="1950" max="2100" required placeholder="2020"></label><label>Пробег, км<input name="mileage" type="number" min="0" required placeholder="75000"></label><label>Город<input name="city" required maxlength="100" placeholder="Самара"></label><label>Состояние<select name="condition"><option value="excellent">Отличное</option><option value="good" selected>Хорошее</option><option value="requires_repair">Требует ремонта</option><option value="damaged">После ДТП</option></select></label></div><label>Телефон<input name="phone" type="tel" required maxlength="30" autocomplete="tel"></label><label>Комментарий<textarea name="comment" maxlength="1000" rows="3" placeholder="Комплектация, владельцы, особенности состояния"></textarea></label><label class="trade-in-consent"><input name="consent" type="checkbox" required><span>Согласен на обработку персональных данных и связь со мной по заявке. Итоговая стоимость определяется после осмотра.</span></label><button class="primary-btn" type="submit">Получить предварительную оценку</button></form></div></div>`);
  const modal=document.querySelector('#tradeInModal'),form=document.querySelector('#tradeInForm'),brandChoice=form.elements.brandChoice,modelChoice=form.elements.modelChoice,customBrand=form.elements.customBrand,customModel=form.elements.customModel,other='__other__',escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function catalog(){return window.vklucheVehicleCatalog?.()||{}}
  function fillTradeInBrands(){const current=brandChoice.value,brands=Object.keys(catalog()).sort((a,b)=>a.localeCompare(b,'ru'));brandChoice.innerHTML=`<option value="">Выберите марку</option>${brands.map(brand=>`<option value="${escape(brand)}">${escape(brand)}</option>`).join('')}<option value="${other}">Другое</option>`;brandChoice.value=brands.includes(current)?current:''}
  function showCustom(select,input,show){select.required=true;input.hidden=!show;input.required=show;if(!show)input.value=''}
  function fillTradeInModels(){const isOther=brandChoice.value===other;showCustom(brandChoice,customBrand,isOther);if(isOther){modelChoice.innerHTML=`<option value="${other}">Другая модель</option>`;modelChoice.disabled=false;showCustom(modelChoice,customModel,true);customBrand.focus();return}showCustom(modelChoice,customModel,false);const models=catalog()[brandChoice.value]||[];modelChoice.innerHTML=models.length?`<option value="">Выберите модель</option>${models.map(model=>`<option value="${escape(model)}">${escape(model)}</option>`).join('')}<option value="${other}">Другое</option>`:'<option value="">Сначала выберите марку</option>';modelChoice.disabled=!models.length}
  brandChoice.addEventListener('change',fillTradeInModels);modelChoice.addEventListener('change',()=>{const isOther=modelChoice.value===other;showCustom(modelChoice,customModel,isOther);if(isOther)customModel.focus()});window.addEventListener('vkluche:vehicle-catalog-ready',fillTradeInBrands);fillTradeInBrands();
  function close(){modal.classList.remove('open');document.body.style.overflow=document.querySelector('#carDetail')?.classList.contains('open')?'hidden':''}
  function open(){if(!window.vklucheAuth?.require(open))return;const inCard=document.querySelector('#carDetail')?.classList.contains('open'),car=inCard?window.vklucheCurrentCar?.():null,meta=window.vklucheAuth.getUser()?.user_metadata||{};document.querySelector('#tradeInTarget').textContent=car?.name||'Оценка без привязки к покупке';form.reset();showCustom(brandChoice,customBrand,false);showCustom(modelChoice,customModel,false);fillTradeInBrands();modelChoice.innerHTML='<option value="">Сначала выберите марку</option>';modelChoice.disabled=true;form.elements.phone.value=meta.phone||'';form.dataset.listingId=car?.listingId||'';form.dataset.vehicle=car?.name||'';modal.classList.add('open');document.body.style.overflow='hidden'}
  document.querySelectorAll('.open-trade-in').forEach(button=>button.addEventListener('click',open));window.addEventListener('vkluche:open-trade-in',open);document.querySelectorAll('[data-trade-in-close]').forEach(item=>item.addEventListener('click',close));
  form.addEventListener('submit',async event=>{event.preventDefault();const client=window.vklucheAuth?.getClient?.(),user=window.vklucheAuth?.getUser?.();if(!client||!user)return;const data=new FormData(form),brand=brandChoice.value===other?String(data.get('customBrand')||'').trim():String(data.get('brandChoice')||'').trim(),model=modelChoice.value===other?String(data.get('customModel')||'').trim():String(data.get('modelChoice')||'').trim();if(!brand||!model)return window.toast?.('Выберите марку и модель');const submit=event.submitter;submit.disabled=true;submit.textContent='Отправляем…';const{error}=await client.from('trade_in_requests').insert({user_id:user.id,target_listing_id:form.dataset.listingId||null,target_vehicle:form.dataset.vehicle||null,brand,model,production_year:+data.get('year'),mileage:+data.get('mileage'),city:String(data.get('city')).trim(),condition:String(data.get('condition')),phone:String(data.get('phone')).trim(),comment:String(data.get('comment')).trim()||null,personal_data_consent:true,consent_at:new Date().toISOString()});submit.disabled=false;submit.textContent='Получить предварительную оценку';if(error)return window.toast?.(`Заявка не отправлена: ${error.message}`);close();window.toast?.('Заявка принята. Статус появится в личном кабинете');window.dispatchEvent(new CustomEvent('vkluche:trade-in-changed'))});
})();
