(()=>{
  const anchor=document.querySelector('#openTradeIn');if(!anchor)return;
  const button=document.createElement('button');button.type='button';button.id='openViewing';button.className='viewing-open';button.textContent='Записаться на осмотр';anchor.before(button);
  document.body.insertAdjacentHTML('beforeend',`<div class="modal viewing-modal" id="viewingModal" role="dialog" aria-modal="true" aria-labelledby="viewingTitle"><div class="modal-backdrop" data-viewing-close></div><div class="modal-card viewing-card"><button class="modal-close" type="button" data-viewing-close>×</button><span class="eyebrow blue">ВСТРЕЧА С ПРОДАВЦОМ</span><h2 id="viewingTitle">Запись на осмотр</h2><p id="viewingVehicle"></p><form id="viewingForm"><label>Желаемые дата и время<input name="preferredAt" type="datetime-local" required></label><label>Запасные дата и время<input name="alternateAt" type="datetime-local"></label><label>Телефон<input name="phone" type="tel" required maxlength="30" autocomplete="tel"></label><label>Комментарий<textarea name="comment" rows="3" maxlength="700" placeholder="Например, хочу провести диагностику в сервисе"></textarea></label><label class="viewing-consent"><input name="consent" type="checkbox" required><span>Согласен на обработку контактных данных и передачу их продавцу для согласования осмотра.</span></label><button class="primary-btn" type="submit">Отправить запрос продавцу</button></form></div></div>`);
  const modal=document.querySelector('#viewingModal'),form=document.querySelector('#viewingForm'),local=value=>{const date=new Date(value);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,16)};
  function close(){modal.classList.remove('open');document.body.style.overflow=document.querySelector('#carDetail')?.classList.contains('open')?'hidden':''}
  function open(){if(!window.vklucheAuth?.require(open))return;const car=window.vklucheCurrentCar?.();if(!car?.listingId)return window.toast?.('Запись доступна только для опубликованных объявлений');const start=new Date(Date.now()+24*60*60*1000);start.setMinutes(0,0,0);form.reset();form.elements.preferredAt.min=local(new Date(Date.now()+60*60*1000));form.elements.preferredAt.value=local(start);form.elements.phone.value=window.vklucheAuth.getUser()?.user_metadata?.phone||'';form.dataset.listingId=car.listingId;document.querySelector('#viewingVehicle').textContent=car.name;modal.classList.add('open');document.body.style.overflow='hidden'}
  button.addEventListener('click',open);document.querySelectorAll('[data-viewing-close]').forEach(item=>item.addEventListener('click',close));
  form.addEventListener('submit',async event=>{event.preventDefault();const client=window.vklucheAuth?.getClient?.(),user=window.vklucheAuth?.getUser?.(),data=new FormData(form),preferred=new Date(String(data.get('preferredAt')));if(preferred<=new Date())return window.toast?.('Выберите будущую дату осмотра');const submit=event.submitter;submit.disabled=true;submit.textContent='Отправляем…';const alternate=data.get('alternateAt');const{error}=await client.from('vehicle_viewing_requests').insert({user_id:user.id,listing_id:form.dataset.listingId,seller_id:user.id,preferred_at:preferred.toISOString(),alternate_at:alternate?new Date(String(alternate)).toISOString():null,phone:String(data.get('phone')).trim(),comment:String(data.get('comment')).trim()||null,personal_data_consent:true});submit.disabled=false;submit.textContent='Отправить запрос продавцу';if(error)return window.toast?.(error.code==='23505'?'У вас уже есть активная запись на этот автомобиль':error.message);close();window.toast?.('Запрос отправлен продавцу');window.dispatchEvent(new CustomEvent('vkluche:viewings-changed'))});
})();
