import { createClient } from 'npm:@supabase/supabase-js@2'
import { maxCa } from './max-ca.ts'
const url=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,token=Deno.env.get('MAX_BOT_TOKEN')!,secret=Deno.env.get('MAX_WEBHOOK_SECRET')||'',admin=createClient(url,key,{auth:{persistSession:false}}),client=Deno.createHttpClient({caCerts:[maxCa]}),site='https://andreyprokashev-sudo.github.io/vkluche-auto-market/'
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'authorization, apikey, content-type, x-client-info, x-supabase-api-version'},headers={Authorization:token,'Content-Type':'application/json'},mf=(u:string,o:RequestInit={})=>fetch(u,{...o,client} as RequestInit),rub=(n:number)=>new Intl.NumberFormat('ru-RU').format(n)+' ₽'
const keys=(a?:string,l?:string)=>a?[{type:'inline_keyboard',payload:{buttons:[[{type:'link',text:'Открыть автомобиль',url:`${site}?listing=${l||''}`}],[{type:'callback',text:'Сделать ставку',payload:`bid:${a}`}],[{type:'callback',text:'Мне интересно',payload:`interest:${a}`},{type:'callback',text:'Задать вопрос',payload:`question:${a}`}],[{type:'callback',text:'Не уведомлять об этом лоте',payload:`mute:${a}`}]]}}]:undefined
async function send(chat:string,text:string,a?:string,l?:string){const r=await mf(`https://platform-api2.max.ru/messages?chat_id=${encodeURIComponent(chat)}`,{method:'POST',headers,body:JSON.stringify({text,attachments:keys(a,l)})});if(!r.ok)console.error(await r.text())}
async function me(){const r=await mf('https://platform-api2.max.ru/me',{headers}),d=await r.json();if(!r.ok)throw Error(d.message||`MAX ${r.status}`);return d}
function input(b:any){const m=b.message||b.callback?.message||{};return{chat:String(b.chat_id||m.recipient?.chat_id||m.chat_id||''),uid:String(b.user?.user_id||m.sender?.user_id||''),text:String(m.body?.text||''),payload:String(b.callback?.payload||'')}}
async function account(chat:string){return(await admin.from('notification_preferences').select('user_id').eq('max_chat_id',chat).maybeSingle()).data}
async function lot(id:string){const{data:a}=await admin.from('auctions').select('id,listing_id,status,start_price,bid_step,ends_at,listings(data),auction_bids(amount)').eq('id',id).maybeSingle();if(!a)return null;const current=Math.max(+a.start_price,...((a.auction_bids||[]) as any[]).map(b=>+b.amount||0)),car=(a.listings as any)?.data||{};return{...a,current,next:current+(+a.bid_step),name:car.name||[car.details?.brand,car.details?.model].filter(Boolean).join(' ')||'Автомобиль'}}
async function remember(chat:string,user:string,a:any,state='idle'){await admin.from('max_bot_dialogs').upsert({chat_id:chat,user_id:user,current_auction_id:a?.id||null,current_listing_id:a?.listing_id||null,state,updated_at:new Date().toISOString()})}
async function act(chat:string,user:string,id:string,action:string,text=''){const a=await lot(id);if(!a)return send(chat,'Этот аукцион уже недоступен.');await remember(chat,user,a);if(action==='interest'){await admin.from('auction_watchers').upsert({auction_id:a.id,user_id:user});return send(chat,`Добавил «${a.name}» в отслеживаемые. Сообщу о важных изменениях.`,a.id,a.listing_id)}if(action==='mute'){await admin.from('max_auction_mutes').upsert({auction_id:a.id,user_id:user});return send(chat,`Уведомления MAX по лоту «${a.name}» отключены.`)}if(action==='question'){await remember(chat,user,a,'awaiting_question');return send(chat,`Напишите вопрос по «${a.name}» одним сообщением. Я передам его продавцу.`)}if(action==='ask'&&text.trim().length>1){await admin.from('auction_questions').insert({auction_id:a.id,author_id:user,question:text.trim().slice(0,1000)});await remember(chat,user,a);return send(chat,'Вопрос передан продавцу. Ответ придёт в уведомлениях.',a.id,a.listing_id)}if(action==='end')return send(chat,`Торги по «${a.name}» завершатся ${new Date(a.ends_at).toLocaleString('ru-RU',{timeZone:'Europe/Samara'})} (самарское время).`,a.id,a.listing_id);if(action==='inspection')return send(chat,`Запись на осмотр «${a.name}» оформляется на сайте: там можно выбрать дату и время.`,a.id,a.listing_id);return send(chat,`${a.name}\nТекущая цена: ${rub(a.current)}\nШаг: ${rub(+a.bid_step)}\nМинимальная следующая ставка: ${rub(a.next)}\n\nСтавка подтверждается только на сайте — бот ставки не принимает.`,a.id,a.listing_id)}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});const b=await req.json().catch(()=>({}))
 if(b.action==='demo'&&secret&&req.headers.get('x-setup-secret')===secret){const email=String(b.email||'').toLowerCase(),{data:u}=await admin.auth.admin.listUsers({page:1,perPage:1000}),user=u?.users.find(x=>x.email?.toLowerCase()===email);if(!user)return Response.json({error:'Пользователь не найден'},{status:404});const{data:p}=await admin.from('notification_preferences').select('max_enabled,max_chat_id').eq('user_id',user.id).maybeSingle();if(!p?.max_enabled||!p.max_chat_id)return Response.json({error:'MAX не подключён'},{status:400});await send(String(p.max_chat_id),String(b.text||'Тестовое уведомление ВКЛЮЧЕ'));return Response.json({sent:true})}
 if(b.action==='setup'&&secret&&req.headers.get('x-setup-secret')===secret){try{await mf('https://platform-api2.max.ru/subscriptions',{method:'DELETE',headers});const webhookUrl=`${url}/functions/v1/max-webhook`,r=await mf('https://platform-api2.max.ru/subscriptions',{method:'POST',headers,body:JSON.stringify({url:webhookUrl,update_types:['bot_started','bot_stopped','message_created','message_callback'],secret})}),d=await r.json().catch(()=>({}));if(!r.ok)return Response.json({error:d.message||`MAX ${r.status}`,details:d},{status:502});await mf('https://platform-api2.max.ru/me/commands',{method:'PATCH',headers,body:JSON.stringify({commands:[{name:'help',description:'Что умеет бот'},{name:'auctions',description:'Текущий аукцион'},{name:'notifications',description:'Настройка уведомлений'}]})});return Response.json({configured:true,bot:await me(),webhookUrl})}catch(e){return Response.json({error:(e as Error).message},{status:502})}}
 if(b.action==='connect'||b.action==='test'){const jwt=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'')||'',{data:{user}}=await admin.auth.getUser(jwt);if(!user)return Response.json({error:'Войдите в аккаунт'},{status:401,headers:cors});if(b.action==='test'){const{data:p}=await admin.from('notification_preferences').select('max_enabled,max_chat_id').eq('user_id',user.id).maybeSingle();if(!p?.max_enabled||!p.max_chat_id)return Response.json({error:'Сначала подключите MAX'},{status:400,headers:cors});await send(String(p.max_chat_id),'Бот работает. Ответьте: «Мне интересно», «Дай подробности», «Какая ставка?» или «Когда закончится?».');return Response.json({sent:true},{headers:cors})}const t=crypto.randomUUID().replaceAll('-',''),expiresAt=new Date(Date.now()+900000).toISOString();await admin.from('max_connection_tokens').insert({token:t,user_id:user.id,expires_at:expiresAt});const bot=await me(),name=bot.username||bot.link?.split('/').pop()||bot.name;return Response.json({url:`https://max.ru/${encodeURIComponent(name)}?start=${t}`,botName:bot.name||name,expiresAt},{headers:cors})}
 if(secret&&req.headers.get('x-max-bot-api-secret')!==secret)return Response.json({error:'invalid secret'},{status:401});const i=input(b)
 if(b.update_type==='bot_started'){const{data:c}=await admin.from('max_connection_tokens').select('*').eq('token',String(b.payload||'')).is('used_at',null).gt('expires_at',new Date().toISOString()).maybeSingle();if(!c){await send(i.chat,'Ссылка устарела. Создайте новую в личном кабинете.');return Response.json({ok:true})}await admin.from('notification_preferences').upsert({user_id:c.user_id,max_chat_id:i.chat,max_enabled:true,updated_at:new Date().toISOString()});await admin.from('user_consents').insert({user_id:c.user_id,document_code:'channel_max',document_version:'2026-08-25',granted:true,granted_at:new Date().toISOString(),metadata:{source:'max_bot',max_user_id:i.uid}});await admin.from('max_connection_tokens').update({used_at:new Date().toISOString()}).eq('token',c.token);await send(i.chat,'MAX подключён. Команда /help покажет подсказки.');return Response.json({ok:true})}
 const p=await account(i.chat);if(!p)return Response.json({ok:true});if(b.update_type==='bot_stopped'){await admin.from('notification_preferences').update({max_enabled:false,max_chat_id:null,updated_at:new Date().toISOString()}).eq('user_id',p.user_id);await admin.from('user_consents').insert({user_id:p.user_id,document_code:'channel_max',document_version:'2026-08-25',granted:false,revoked_at:new Date().toISOString(),metadata:{source:'max_bot_stopped'}});return Response.json({ok:true})}
 const cb=i.payload.match(/^(bid|interest|question|mute):([0-9a-f-]+)$/i);if(cb){await act(i.chat,p.user_id,cb[2],cb[1]==='bid'?'details':cb[1]);return Response.json({ok:true})}
 if(b.update_type==='message_created'){const{data:d}=await admin.from('max_bot_dialogs').select('*').eq('chat_id',i.chat).maybeSingle(),n=i.text.trim().toLowerCase();if(d?.state==='awaiting_question'&&d.current_auction_id)await act(i.chat,p.user_id,d.current_auction_id,'ask',i.text);else if(d?.current_auction_id&&/(интерес|подпис|след)/.test(n))await act(i.chat,p.user_id,d.current_auction_id,'interest');else if(d?.current_auction_id&&/(ставк|подроб|цена|аукцион)/.test(n))await act(i.chat,p.user_id,d.current_auction_id,'details');else if(d?.current_auction_id&&/(когда|законч|время)/.test(n))await act(i.chat,p.user_id,d.current_auction_id,'end');else if(d?.current_auction_id&&/(осмотр|посмотр)/.test(n))await act(i.chat,p.user_id,d.current_auction_id,'inspection');else await send(i.chat,'Я отвечаю по последнему аукциону из уведомления. Напишите: «Мне интересно», «Дай подробности», «Какая ставка?», «Когда закончится?» или нажмите «Задать вопрос». Ставки подтверждаются только на сайте.')}
 return Response.json({ok:true})})
