import { createClient } from 'npm:@supabase/supabase-js@2'
const url=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,token=Deno.env.get('TELEGRAM_BOT_TOKEN')!,secret=Deno.env.get('TELEGRAM_WEBHOOK_SECRET')||'',admin=createClient(url,key,{auth:{persistSession:false}}),api=`https://api.telegram.org/bot${token}`,site='https://andreyprokashev-sudo.github.io/vkluche-auto-market/',cors={'access-control-allow-origin':'*','access-control-allow-headers':'authorization, apikey, content-type, x-client-info, x-supabase-api-version'},rub=(n:number)=>new Intl.NumberFormat('ru-RU').format(n)+' ₽'
async function call(method:string,body:any={}){const r=await fetch(`${api}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!d.ok)throw Error(d.description||`Telegram ${r.status}`);return d.result}
const keyboard=(a:any)=>({inline_keyboard:[[{text:'Открыть автомобиль',url:`${site}?listing=${a.listing_id}`}],[{text:'Сделать ставку',url:`${site}?listing=${a.listing_id}`}],[{text:'Мне интересно',callback_data:`interest:${a.id}`},{text:'Задать вопрос',callback_data:`question:${a.id}`}],[{text:'Не уведомлять об этом лоте',callback_data:`mute:${a.id}`}]]})
async function send(chat:string,text:string,a?:any,markup?:any){return call('sendMessage',{chat_id:chat,text,reply_markup:markup||a&&keyboard(a)})}
async function account(chat:string){return(await admin.from('notification_preferences').select('user_id').eq('telegram_chat_id',chat).maybeSingle()).data}
async function lot(id:string){const{data:a}=await admin.from('auctions').select('id,listing_id,status,start_price,bid_step,ends_at,listings(data),auction_bids!auction_bids_auction_id_fkey(amount)').eq('id',id).maybeSingle();if(!a)return null;const current=Math.max(+a.start_price,...((a.auction_bids||[]) as any[]).map(b=>+b.amount||0)),car=(a.listings as any)?.data||{};return{...a,current,next:current+(+a.bid_step),name:car.name||[car.details?.brand,car.details?.model].filter(Boolean).join(' ')||'Автомобиль'}}
async function remember(chat:string,user:string,a:any,state='idle'){await admin.from('telegram_bot_dialogs').upsert({chat_id:chat,user_id:user,current_auction_id:a.id,current_listing_id:a.listing_id,state,updated_at:new Date().toISOString()})}
async function choose(chat:string){const{data=[]}=await admin.from('auctions').select('id,listing_id,listings(data)').in('status',['active','scheduled']).order('ends_at').limit(8);if(!data.length)return send(chat,'Сейчас активных или запланированных аукционов нет.');return send(chat,'Выберите аукцион:',null,{inline_keyboard:data.map((a:any)=>[{text:String(a.listings?.data?.name||'Автомобиль').slice(0,50),callback_data:`details:${a.id}`}])})}
async function act(chat:string,user:string,id:string,action:string,text=''){const a=await lot(id);if(!a)return send(chat,'Этот аукцион завершён или недоступен. Выберите другой: /auctions');await remember(chat,user,a);if(action==='interest'){await admin.from('auction_watchers').upsert({auction_id:a.id,user_id:user});return send(chat,`Добавил «${a.name}» в отслеживаемые.`,a)}if(action==='mute'){await admin.from('telegram_auction_mutes').upsert({auction_id:a.id,user_id:user});return send(chat,`Уведомления Telegram по лоту «${a.name}» отключены.`)}if(action==='question'){await remember(chat,user,a,'awaiting_question');return send(chat,`Напишите вопрос по «${a.name}» одним сообщением.`)}if(action==='ask'){await admin.from('auction_questions').insert({auction_id:a.id,author_id:user,question:text.trim().slice(0,1000)});await remember(chat,user,a);return send(chat,'Вопрос передан продавцу. Ответ придёт в уведомлениях.',a)}if(action==='end')return send(chat,`Торги по «${a.name}» завершатся ${new Date(a.ends_at).toLocaleString('ru-RU',{timeZone:'Europe/Samara'})} (самарское время).`,a);if(action==='inspection')return send(chat,`Запись на осмотр «${a.name}» оформляется на сайте.`,a);return send(chat,`${a.name}\nТекущая цена: ${rub(a.current)}\nШаг: ${rub(+a.bid_step)}\nМинимальная следующая ставка: ${rub(a.next)}\n\nСтавка подтверждается только на сайте.`,a)}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});const b=await req.json().catch(()=>({}))
 if(b.action==='setup'&&secret&&req.headers.get('x-setup-secret')===secret){try{const webhookUrl=`${url}/functions/v1/telegram-webhook`;await call('setWebhook',{url:webhookUrl,secret_token:secret,allowed_updates:['message','callback_query']});await call('setMyCommands',{commands:[{command:'start',description:'Подключить уведомления'},{command:'auctions',description:'Выбрать аукцион'},{command:'help',description:'Что умеет бот'},{command:'settings',description:'Настройки уведомлений'}]});return Response.json({configured:true,bot:await call('getMe'),webhookUrl})}catch(e){return Response.json({error:(e as Error).message},{status:502})}}
 if(b.action==='connect'||b.action==='test'){const jwt=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'')||'',{data:{user}}=await admin.auth.getUser(jwt);if(!user)return Response.json({error:'Войдите в аккаунт'},{status:401,headers:cors});if(b.action==='test'){const{data:p}=await admin.from('notification_preferences').select('telegram_enabled,telegram_chat_id').eq('user_id',user.id).maybeSingle();if(!p?.telegram_enabled||!p.telegram_chat_id)return Response.json({error:'Сначала подключите Telegram'},{status:400,headers:cors});await send(String(p.telegram_chat_id),'Тестовое уведомление ВКЛЮЧЕ. Telegram подключён и работает.');return Response.json({sent:true},{headers:cors})}const t=crypto.randomUUID().replaceAll('-',''),expiresAt=new Date(Date.now()+900000).toISOString();await admin.from('telegram_connection_tokens').insert({token:t,user_id:user.id,expires_at:expiresAt});const bot=await call('getMe');return Response.json({url:`https://t.me/${bot.username}?start=${t}`,botName:bot.first_name||bot.username,expiresAt},{headers:cors})}
 if(secret&&req.headers.get('x-telegram-bot-api-secret-token')!==secret)return Response.json({error:'invalid secret'},{status:401});const message=b.message||b.callback_query?.message,chat=String(message?.chat?.id||''),text=String(b.message?.text||''),callback=String(b.callback_query?.data||'')
 if(callback){await call('answerCallbackQuery',{callback_query_id:b.callback_query.id});const p=await account(chat),m=callback.match(/^(details|interest|question|mute):([0-9a-f-]+)$/i);if(p&&m)await act(chat,p.user_id,m[2],m[1]);return Response.json({ok:true})}
 const start=text.match(/^\/start\s+([A-Za-z0-9_-]+)$/);if(start){const{data:c}=await admin.from('telegram_connection_tokens').select('*').eq('token',start[1]).is('used_at',null).gt('expires_at',new Date().toISOString()).maybeSingle();if(!c){await send(chat,'Ссылка подключения устарела. Создайте новую в личном кабинете.');return Response.json({ok:true})}await admin.from('notification_preferences').upsert({user_id:c.user_id,telegram_chat_id:chat,telegram_enabled:true,updated_at:new Date().toISOString()});await admin.from('user_consents').insert({user_id:c.user_id,document_code:'channel_telegram',document_version:'2026-08-25',granted:true,granted_at:new Date().toISOString(),metadata:{source:'telegram_bot',telegram_user_id:String(message.from?.id||'')}});await admin.from('telegram_connection_tokens').update({used_at:new Date().toISOString()}).eq('token',c.token);await send(chat,'Telegram подключён. Напишите /auctions, чтобы выбрать торги.');return Response.json({ok:true})}
 const p=await account(chat);if(!p){await send(chat,'Подключите Telegram в личном кабинете ВКЛЮЧЕ, затем откройте персональную ссылку подключения.');return Response.json({ok:true})}const{data:d}=await admin.from('telegram_bot_dialogs').select('*').eq('chat_id',chat).maybeSingle(),n=text.trim().toLowerCase(),has=Boolean(d?.current_auction_id);if(n==='/help'||n==='/start')await send(chat,'Я помогу с аукционами. Команда /auctions показывает торги. После выбора можно написать: «Мне интересно», «Дай подробности», «Какая ставка?», «Когда закончится?» или «Хочу посмотреть». Ставка подтверждается только на сайте.');else if(n==='/settings')await send(chat,'Каналы и события настраиваются в личном кабинете ВКЛЮЧЕ.',null,{inline_keyboard:[[{text:'Открыть настройки',url:site}]]});else if(n==='/auctions'||!has)await choose(chat);else if(d.state==='awaiting_question'&&text.trim().length>1)await act(chat,p.user_id,d.current_auction_id,'ask',text);else if(/(интер|интр|подпис|след)/.test(n))await act(chat,p.user_id,d.current_auction_id,'interest');else if(/(став|подроб|подоб|цена|аукцион)/.test(n))await act(chat,p.user_id,d.current_auction_id,'details');else if(/(когда|конч|время)/.test(n))await act(chat,p.user_id,d.current_auction_id,'end');else if(/(осмотр|посмотр)/.test(n))await act(chat,p.user_id,d.current_auction_id,'inspection');else await send(chat,'Напишите: «Мне интересно», «Дай подробности», «Какая ставка?», «Когда закончится?» или выберите /auctions.');return Response.json({ok:true})})
